accessing
colorXImage
	^(PDF classAt: #ImageXObject)
		on: ((Valuemap new: 8)
			add: #Subtype -> #Image;
			add: #Type -> #XObject;
			add: #Width -> 98;
			add: #Height -> 91;
			add: #BitsPerComponent -> 8;
			add: #ColorSpace -> ((PDF classAt: #Indexed)
				base: #DeviceRGB
				number: 127
				bytes: (ByteArray fromASCII85String: '&o=T8o_JFara__EcJe2S^"=f_ZmC%(!+;O*S&MPUimm/[nFl^/ZI5Mghi51tdGs]KkjlRDl2(>V!*Gi
	(e`Tep_M,DI3/4uOdcD3_X9E14i9^))NkP/_r(<*d!+)B-CT29Ob^H_C!bJ2.<1J9;d,sil!*c,8h!8^
	Ob/rQ-Qb_>Mqu&:%\$FBAWQO-nPJ@WDWctPjh!4K>T>qFVW#9TWRDIVtFg$V1eXsh:VTIaZLq5Hs\E!#
	Mo_A:d@\a9@V*^-R<g^hhnb4Vc[39au)K`,QO1suPpuUu<Wm''F;V9<PIb+6H**HSB*Wm:20qS1\I][u
	B(lh&flnSbANF/mM.FKY[>R"DZnlLXclG-BchoQ$qU&nRpAA#+"?bQVXW#AC%;@A<g3U]=\o!*l/s>bM
	.-V#Y#$!+)?!@A<j4Ud0jNO1X$WBW''hVoXE?4YKu6JVp([Kgf0?KJ?@,t?(qX<V`9@>&oXiNs8N(0V>
	pSq~>'));
			add: #Length -> 2040;
			add: #Filter -> #FlateDecode;
			yourself)
		externalBytes: (ByteArray fromASCII85String: 'GhVPQm6fko(<5H)Lrd1VLn[=8is6i<eVc,=,2he4Gh(4-]''bU4["UP%c?4?oP0UhV.C9AWMBI<$o80
	8WIS%gFaceIk?R^-O*Ze!]*QGiD()K&K!_e)K*Q+%?#aZS!^/0JGL09J+/csC$#c/%)&)`7^D&ZtpCjZ
	?F;gX5f;!:UA4FgB`:56LQ1lqW]MX`s3[mH`X+Qu5f6Jh3Y"RFlcSn0>Y=edJaXq7i''"0#eed65C`FB
	7ZJ)^in>&Fc3V!7n*#9SejWfnY/1-a_EN&Jg!\hDma=Io"8rUjGslLBMSo;\3NW6akU(nTltN8$LXg<-
	SF02E2e.glhe\rC[Gp]MoDc"u(5&:ng9);:''6+,\+&^ii*js=WfQmI6di=,,Q''1-`,\A]-h5S:gO6;
	,/IggM\Vij;N:`54a]X9cOAY@R7e\++ejL[RSeVJ!6(''jTuGg<AC=!M''''l:#hspQZZI6LDE[71I6V
	sj/PTq''1[N''1c1guq2)=IsWk=X>++c`ZA6:GlKDu+7>T!UJ$V.Kh4kd8HM=PruoK[m?#:F&^.F;[nN
	OKol=9&T&MY*/<WJ)kW?([Oq+@]O99bFii%;L*l7k16DbEZpJk2B&h`O''`SM^QCYX=ogGkA.![MT9"D
	>$p*"$Yf\0EY.=L&_bSd4a$LPfHq*Jl_j\"2DpKD;2@92G$''jj+Z4MUacu8arbKtu2alpI4_#/,/2b_
	mn!\Z;_Do[p9\njfa$.)n9aRJNmP2o^("Xk>["9fW3*hCCOS/cKc+fb5FmZY"G#uI0l\G_u%=<*d7)K*
	*s8naOa;_NH''[C-AM1_!p719=7jQs,i(^t#rk>lqVuNK*P65$853>`//5>Dm?Z!8s0d8cq\.Y-A3WZN
	k.iMV9HId%A7"^M8<fC,7DPl40o!DM%qf^5\t-%He$[-g)iEc`-uI''6om+`nh<1_=9TC";''rdi]@GH
	d:9>D8%l`;BcD$m^/$\ZPcYP="<Ogl;a&EXa6Y/On+L`>7nZJX14dN''%lR,>p&e/uGh*;2?>>/o="Mu
	YJf7Q`RR#pX9o8<`&78VC46d.AE$R&QoWH35[7W\u#QE[pe[8f?.@ij#bNPc=hal\!ab^Oj.T.\gj03W
	9\:*jXNUeuZ^sRI0[XL.H.?rX9Jc]j0dccs?haAlQ4Q4h:(\<I+/kGq2mS!%Lq=>@''bSdYd$$A>e^V3
	.5o3.bCYta:mErlGR@nZDNgRJ8sh[Z/f/We1#W`b-+RLd%V^]9b?Q=[4FI''_U;`a4r9f!("-RRan^0O
	0?gcI8F#Q[dq-$7HhR/t^fMlUSU0Q@GB/=1%^ho0.4E,01@Y<td@Y;h&<t$4J>G!A"F%k;FfI`Y,e1lZ
	GH989X($,[r*M=f`0;_/Z".j*Lb$''HdJ*GHg5$OTj5#JJk.??YO&fm&hPBoK"2+]O0mHd.mC]JJC9+G
	.2O)9R/blpa(.9dVVH#o_;p[8_3rkeZ=D[fHO>0*OJQi#t,rnQii(i[nG?*pXn\G0:c8IY`0SqD*AZTK
	`DH=Ic$7Gba.aii8`[5fO;CdGK`>W_I?aD,E7Xl"A,kEVJ*W.-N9=L,R5/mCtE"7klSLAi`6UP@+k`)I
	]cPoh&pqP3X3qX^^L^*%KSBm0S&OU&A(G_.D=iO@fQr>10`S(5jTNm/GGe1F:cfDgJ&4EE^d6[KE>>r.
	4BA%!%2_mB)sI`S&2TD"''"/8<jnc?Af;m3hi,@Hh;?Ca`5rg;<0g"Z0g''8/:iW*!nK8[]Ae6K*8q74
	!I1[r6)pTcUqqO]kM_@7k.9nKS]p_c#Hle)+q_JdIG+O(''4e5lOr=,*X)?LkqLQW=<`HCuiF+t%KVOV
	^3QPtYG''kBSe;XI&&Ypm=R!''T''P:0L49pg%cTCeC(F^nId^^Fa+4GV6Po0/%*6KW.0TlMb>%$''<0
	38t`UZ34RX?<7$C!H#9qpi;De1B"()\Um._uo)W!i%%)P\!A2MDqcsZi%X>",5gYuk,VE>Z^pti3qlE(
	93rXZ$`+Znr-bc=@p>3VQ8hrUES>B+3Tb,5e#r&b?(O$r`V!+5.Mao[(YZMT+f>L!ZITTaY+MNE"fBII
	ZH?-["n<$-ll:OrRZ@17,e$&5hfsHN4Vm]:/LmY6$pIqMA9`iE$lP^Y=03,JEKqS0(Dg8AqGd+%\\"A4
	`54%qJD%T0Eq,,s%_.aM@21''L>";,GkT%:*05)$@+c*p=g2p%3KoWbg$jT<t#brcYOVW2$D?RJYU+X3
	[EIX8C_Y1"?PXTTm@r:-C\#pEY`9<u@D#Mpk(ruQPLTm#&7+tt8?8ks`#WIN++>rS<!n6f@$d#Xm5>Q-
	cjG7T$B6/%HdIHhnSB4k>OEs/27^EMeFKgH"N,*u27/GmaZ1[Y.X3W29.E9=a-Ni\PFVWtm7I<At^b^2
	lcq(6$U''Im=^OK"Hti^%iA^obpE[s''Ye[\6oOr*XEh1YR$qjUVg""-6]KhaC)I)D=2Vmt1A*q9j`pi
	-W6&^A&S-&HHM>A$(rJpO7hn5CjA(:9E=u/;;^TB''_"`@_"JtZ-kde>o/LSL//7a"-c:JQ=6OMC<`!S
	@Z0C4Y?t&:ESp^Z"N(,.~>')
