outputs
outputText2
	 "Generated on 13. Juni 2021 um 18:14:37"

	^'Report
page width: 612
page height: 792
margin: #(36 36 36 36)
layout: 36 576 756 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 792
maximum Y: 756 (page height - footer)
output parts: 9
#(10 0 0 -10 36 44.7325) PDF has become a de facto global standard for more secure and dependable information exchange since Adobe 
#(10 0 0 -10 36 57.0875) published the complete PDF specification in 1993. Both government and private industry have come to rely on PDF 
#(10 0 0 -10 36 69.4425) for the volumes of electronic records that need to be more securely and reliably shared, managed, and in some 
#(10 0 0 -10 36 81.7975) cases preserved for generations. Since 1995 Adobe has participated in various working groups that develop 
#(10 0 0 -10 36 94.1525) technical specifications for publication by ISO and worked within the ISO process to deliver specialized subsets 
#(10 0 0 -10 36 106.507) of PDF as standards for specific industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange 
#(10 0 0 -10 36 118.862) (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed 
#(10 0 0 -10 36 131.217) standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM serves as the 
#(10 0 0 -10 36 143.572) administrator for PDF/A, PDF/E, PDF/UA and PDF/H.'
