outputs
outputTextLongTwoPages
	 "Generated on 13. Juni 2021 um 18:14:31"

	^'Report
page width: 612
page height: 200
margin: #(0 0 0 0)
layout: 0 612 200 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 2
---
page width: 612
page height: 200
maximum Y: 185.174 (page height - footer)
output parts: 13
''next page'' size: 4
#(12 0 0 -12 0 195.653) This is a footer
#(12 0 0 -12 0 10.479) This text will span multiple pages. Page number: 1 of 10
#(10 0 0 -10 0 23.5585) This header should only be visible on page 1
#(10 0 0 -10 15 50.9135) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document Format (PDF) 
#(10 0 0 -10 15 63.2685) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content Management Association 
#(10 0 0 -10 15 75.6235) (AIIM), for the purpose of publication by the International Organization for Standardization (ISO).PDF has become a de 
#(10 0 0 -10 15 87.9785) facto global standard for more secure and dependable information exchange since Adobe published the complete PDF 
#(10 0 0 -10 15 100.334) specification in 1993. Both government and private industry have come to rely on PDF for the volumes of electronic records 
#(10 0 0 -10 15 112.688) that need to be more securely and reliably shared, managed, and in some cases preserved for generations. Since 1995 Adobe 
#(10 0 0 -10 15 125.043) has participated in various working groups that develop technical specifications for publication by ISO and worked within 
#(10 0 0 -10 15 137.398) the ISO process to deliver specialized subsets of PDF as standards for specific industries and functions. Today, PDF for 
#(10 0 0 -10 15 149.753) Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal 
#(10 0 0 -10 15 162.108) Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. 
---
page width: 612
page height: 200
maximum Y: 172.819 (page height - footer)
output parts: 13
''next page'' size: 3
#(12 0 0 -12 0 183.298) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(12 0 0 -12 0 10.479) This text will span multiple pages. Page number: 2 of 10
#(10 0 0 -10 15 39.076) AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was 
#(10 0 0 -10 15 51.431) prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format version 
#(10 0 0 -10 15 63.786) 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track procedure", by Technical Committee 
#(10 0 0 -10 15 76.141) ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in parallel with its approval by the 
#(10 0 0 -10 15 88.496) ISO member bodies.In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as the 
#(10 0 0 -10 15 100.851) international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site 
#(10 0 0 -10 15 113.206) (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable 
#(10 0 0 -10 15 125.561) Document Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content 
#(10 0 0 -10 15 137.916) Management Association (AIIM), for the purpose of publication by the International Organization for Standardization 
#(10 0 0 -10 15 150.271) (ISO).PDF has become a de facto global standard for more secure and dependable information exchange since Adobe published 
---
page width: 612
page height: 200
maximum Y: 172.819 (page height - footer)
output parts: 13
''next page'' size: 2
#(12 0 0 -12 0 183.298) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(12 0 0 -12 0 10.479) This text will span multiple pages. Page number: 3 of 10
#(10 0 0 -10 15 39.076) the complete PDF specification in 1993. Both government and private industry have come to rely on PDF for the volumes of 
#(10 0 0 -10 15 51.431) electronic records that need to be more securely and reliably shared, managed, and in some cases preserved for generations. 
#(10 0 0 -10 15 63.786) Since 1995 Adobe has participated in various working groups that develop technical specifications for publication by ISO 
#(10 0 0 -10 15 76.141) and worked within the ISO process to deliver specialized subsets of PDF as standards for specific industries and functions. 
#(10 0 0 -10 15 88.496) Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for 
#(10 0 0 -10 15 100.851) Universal Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best 
#(10 0 0 -10 15 113.206) Practice Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 
#(10 0 0 -10 15 125.561) document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document 
#(10 0 0 -10 15 137.916) Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track procedure", by 
#(10 0 0 -10 15 150.271) Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in parallel with 
---
page width: 612
page height: 200
maximum Y: 172.819 (page height - footer)
output parts: 13
''next page'' size: 1
#(12 0 0 -12 0 183.298) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(12 0 0 -12 0 10.479) This text will span multiple pages. Page number: 4 of 10
#(10 0 0 -10 15 39.076) its approval by the ISO member bodies.In January 2008, this ISO technical committee approved the final revised 
#(10 0 0 -10 15 51.431) documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on 
#(10 0 0 -10 15 63.786) the ISO web site (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release 
#(10 0 0 -10 15 76.141) the full Portable Document Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the 
#(10 0 0 -10 15 88.496) Enterprise Content Management Association (AIIM), for the purpose of publication by the International Organization for 
#(10 0 0 -10 15 100.851) Standardization (ISO).PDF has become a de facto global standard for more secure and dependable information exchange since 
#(10 0 0 -10 15 113.206) Adobe published the complete PDF specification in 1993. Both government and private industry have come to rely on PDF for 
#(10 0 0 -10 15 125.561) the volumes of electronic records that need to be more securely and reliably shared, managed, and in some cases preserved 
#(10 0 0 -10 15 137.916) for generations. Since 1995 Adobe has participated in various working groups that develop technical specifications for 
#(10 0 0 -10 15 150.271) publication by ISO and worked within the ISO process to deliver specialized subsets of PDF as standards for specific 
---
page width: 612
page height: 200
maximum Y: 172.819 (page height - footer)
output parts: 12
#(12 0 0 -12 0 183.298) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(12 0 0 -12 0 10.479) This text will span multiple pages. Page number: 5 of 10
#(10 0 0 -10 15 39.076) industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for 
#(10 0 0 -10 15 51.431) Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) 
#(10 0 0 -10 15 63.786) is an AIIM proposed Best Practice Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring 
#(10 0 0 -10 15 76.141) of 2008 the ISO 32000 document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe 
#(10 0 0 -10 15 88.496) Portable Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track 
#(10 0 0 -10 15 100.851) procedure", by Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in 
#(10 0 0 -10 15 113.206) parallel with its approval by the ISO member bodies.In January 2008, this ISO technical committee approved the final revised 
#(10 0 0 -10 15 125.561) documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the 
#(10 0 0 -10 15 137.916) ISO web site (http://www.iso.org).
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 13
''next page'' size: 4
#(10 0 0 -10 0 8.7325) next logical page 6
#(10 0 0 -10 15 36.0875) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document Format (PDF) 
#(10 0 0 -10 15 48.4425) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content Management Association 
#(10 0 0 -10 15 60.7975) (AIIM), for the purpose of publication by the International Organization for Standardization (ISO).PDF has become a de 
#(10 0 0 -10 15 73.1525) facto global standard for more secure and dependable information exchange since Adobe published the complete PDF 
#(10 0 0 -10 15 85.5075) specification in 1993. Both government and private industry have come to rely on PDF for the volumes of electronic records 
#(10 0 0 -10 15 97.8625) that need to be more securely and reliably shared, managed, and in some cases preserved for generations. Since 1995 Adobe 
#(10 0 0 -10 15 110.217) has participated in various working groups that develop technical specifications for publication by ISO and worked within 
#(10 0 0 -10 15 122.572) the ISO process to deliver specialized subsets of PDF as standards for specific industries and functions. Today, PDF for 
#(10 0 0 -10 15 134.927) Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal 
#(10 0 0 -10 15 147.282) Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. 
#(10 0 0 -10 15 159.637) AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was 
#(10 0 0 -10 15 171.992) prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format version 
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 13
''next page'' size: 3
#(10 0 0 -10 0 8.7325) next logical page 7
#(10 0 0 -10 15 36.605) 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track procedure", by Technical Committee 
#(10 0 0 -10 15 48.96) ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in parallel with its approval by the 
#(10 0 0 -10 15 61.315) ISO member bodies.In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as the 
#(10 0 0 -10 15 73.67) international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site 
#(10 0 0 -10 15 86.025) (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable 
#(10 0 0 -10 15 98.38) Document Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content 
#(10 0 0 -10 15 110.735) Management Association (AIIM), for the purpose of publication by the International Organization for Standardization 
#(10 0 0 -10 15 123.09) (ISO).PDF has become a de facto global standard for more secure and dependable information exchange since Adobe published 
#(10 0 0 -10 15 135.445) the complete PDF specification in 1993. Both government and private industry have come to rely on PDF for the volumes of 
#(10 0 0 -10 15 147.8) electronic records that need to be more securely and reliably shared, managed, and in some cases preserved for generations. 
#(10 0 0 -10 15 160.155) Since 1995 Adobe has participated in various working groups that develop technical specifications for publication by ISO 
#(10 0 0 -10 15 172.51) and worked within the ISO process to deliver specialized subsets of PDF as standards for specific industries and functions. 
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 13
''next page'' size: 2
#(10 0 0 -10 0 8.7325) next logical page 8
#(10 0 0 -10 15 36.605) Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for 
#(10 0 0 -10 15 48.96) Universal Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best 
#(10 0 0 -10 15 61.315) Practice Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 
#(10 0 0 -10 15 73.67) document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document 
#(10 0 0 -10 15 86.025) Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track procedure", by 
#(10 0 0 -10 15 98.38) Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in parallel with 
#(10 0 0 -10 15 110.735) its approval by the ISO member bodies.In January 2008, this ISO technical committee approved the final revised 
#(10 0 0 -10 15 123.09) documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on 
#(10 0 0 -10 15 135.445) the ISO web site (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release 
#(10 0 0 -10 15 147.8) the full Portable Document Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the 
#(10 0 0 -10 15 160.155) Enterprise Content Management Association (AIIM), for the purpose of publication by the International Organization for 
#(10 0 0 -10 15 172.51) Standardization (ISO).PDF has become a de facto global standard for more secure and dependable information exchange since 
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 13
''next page'' size: 1
#(10 0 0 -10 0 8.7325) next logical page 9
#(10 0 0 -10 15 36.605) Adobe published the complete PDF specification in 1993. Both government and private industry have come to rely on PDF for 
#(10 0 0 -10 15 48.96) the volumes of electronic records that need to be more securely and reliably shared, managed, and in some cases preserved 
#(10 0 0 -10 15 61.315) for generations. Since 1995 Adobe has participated in various working groups that develop technical specifications for 
#(10 0 0 -10 15 73.67) publication by ISO and worked within the ISO process to deliver specialized subsets of PDF as standards for specific 
#(10 0 0 -10 15 86.025) industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for 
#(10 0 0 -10 15 98.38) Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) 
#(10 0 0 -10 15 110.735) is an AIIM proposed Best Practice Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring 
#(10 0 0 -10 15 123.09) of 2008 the ISO 32000 document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe 
#(10 0 0 -10 15 135.445) Portable Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track 
#(10 0 0 -10 15 147.8) procedure", by Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in 
#(10 0 0 -10 15 160.155) parallel with its approval by the ISO member bodies.In January 2008, this ISO technical committee approved the final revised 
#(10 0 0 -10 15 172.51) documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the 
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 2
#(10 0 0 -10 0 8.7325) next logical page 10
#(10 0 0 -10 15 36.605) ISO web site (http://www.iso.org).'
