outputs
outputImagePNG
	 "Generated on 13. Juni 2021 um 18:14:33"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 4
#(10 0 0 -10 0 8.7325) Show 3 PNG images aligned left, center, right
#(13.5 0 0 -13.5 0 25.855) [image] 
#(13.5 0 0 -13.5 117.0 39.355) [image] 
#(12.0 0 0 -12.0 236 51.355) [image] '
