outputs
outputTextLongPageNumberReset
	 "Generated on 13. Juni 2021 um 18:14:32"

	^'Report
page width: 612
page height: 200
margin: #(0 0 0 0)
layout: 0 612 200 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 2
---
page width: 612
page height: 200
maximum Y: 187.645 (page height - footer)
output parts: 15
''next page'' size: 1
#(10 0 0 -10 0 196.378) Page 1 of 2, and in report 4
24.75 @ 25 line: 587.25 @ 25 0.5
587 @ 25 line: 587 @ 162.645 0.5
24.75 @ 162.645 line: 587.25 @ 162.645 0.5
25 @ 162.645 line: 25 @ 25 0.5
#(10 0 0 -10 30 38.7325) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document 
#(10 0 0 -10 30 51.0875) Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content 
#(10 0 0 -10 30 63.4425) Management Association (AIIM), for the purpose of publication by the International Organization for Standardization 
#(10 0 0 -10 30 75.7975) (ISO).PDF has become a de facto global standard for more secure and dependable information exchange since Adobe 
#(10 0 0 -10 30 88.1525) published the complete PDF specification in 1993. Both government and private industry have come to rely on PDF for 
#(10 0 0 -10 30 100.507) the volumes of electronic records that need to be more securely and reliably shared, managed, and in some cases 
#(10 0 0 -10 30 112.862) preserved for generations. Since 1995 Adobe has participated in various working groups that develop technical 
#(10 0 0 -10 30 125.217) specifications for publication by ISO and worked within the ISO process to deliver specialized subsets of PDF as 
#(10 0 0 -10 30 137.572) standards for specific industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are 
#(10 0 0 -10 30 149.927) ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed standards. 
---
page width: 612
page height: 200
maximum Y: 187.645 (page height - footer)
output parts: 13
#(10 0 0 -10 0 196.378) Page 2 of 2, and in report 4
24.75 @ 25.5175 line: 587.25 @ 25.5175 0.5
587 @ 25.5175 line: 587 @ 162.645 0.5
24.75 @ 162.645 line: 587.25 @ 162.645 0.5
25 @ 162.645 line: 25 @ 25.5175 0.5
#(10 0 0 -10 30 39.25) Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM serves as the administrator 
#(10 0 0 -10 30 51.605) for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems 
#(10 0 0 -10 30 63.96) Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format version 1.7, November 2006) 
#(10 0 0 -10 30 76.315) and was reviewed, edited and adopted, under a special "fast-track procedure", by Technical Committee ISO/TC 171, 
#(10 0 0 -10 30 88.67) Document management application, Subcommittee SC 2, Application issues, in parallel with its approval by the ISO 
#(10 0 0 -10 30 101.025) member bodies.In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as 
#(10 0 0 -10 30 113.38) the international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site 
#(10 0 0 -10 30 125.735) (http://www.iso.org).
---
page width: 612
page height: 200
maximum Y: 187.645 (page height - footer)
output parts: 15
''next page'' size: 1
#(10 0 0 -10 0 196.378) Page 1 of 2, and in report 4
#(10 0 0 -10 0 8.7325) show have new page number
24.75 @ 37.355 line: 587.25 @ 37.355 0.5
587 @ 37.355 line: 587 @ 162.645 0.5
24.75 @ 162.645 line: 587.25 @ 162.645 0.5
25 @ 162.645 line: 25 @ 37.355 0.5
#(10 0 0 -10 30 51.0875) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document 
#(10 0 0 -10 30 63.4425) Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content 
#(10 0 0 -10 30 75.7975) Management Association (AIIM), for the purpose of publication by the International Organization for Standardization 
#(10 0 0 -10 30 88.1525) (ISO).PDF has become a de facto global standard for more secure and dependable information exchange since Adobe 
#(10 0 0 -10 30 100.507) published the complete PDF specification in 1993. Both government and private industry have come to rely on PDF for 
#(10 0 0 -10 30 112.862) the volumes of electronic records that need to be more securely and reliably shared, managed, and in some cases 
#(10 0 0 -10 30 125.217) preserved for generations. Since 1995 Adobe has participated in various working groups that develop technical 
#(10 0 0 -10 30 137.572) specifications for publication by ISO and worked within the ISO process to deliver specialized subsets of PDF as 
#(10 0 0 -10 30 149.927) standards for specific industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are 
---
page width: 612
page height: 200
maximum Y: 187.645 (page height - footer)
output parts: 14
#(10 0 0 -10 0 196.378) Page 2 of 2, and in report 4
24.75 @ 25.5175 line: 587.25 @ 25.5175 0.5
587 @ 25.5175 line: 587 @ 162.645 0.5
24.75 @ 162.645 line: 587.25 @ 162.645 0.5
25 @ 162.645 line: 25 @ 25.5175 0.5
#(10 0 0 -10 30 39.25) ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed standards. 
#(10 0 0 -10 30 51.605) Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM serves as the administrator 
#(10 0 0 -10 30 63.96) for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems 
#(10 0 0 -10 30 76.315) Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format version 1.7, November 2006) 
#(10 0 0 -10 30 88.67) and was reviewed, edited and adopted, under a special "fast-track procedure", by Technical Committee ISO/TC 171, 
#(10 0 0 -10 30 101.025) Document management application, Subcommittee SC 2, Application issues, in parallel with its approval by the ISO 
#(10 0 0 -10 30 113.38) member bodies.In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as 
#(10 0 0 -10 30 125.735) the international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site 
#(10 0 0 -10 30 138.09) (http://www.iso.org).'
