outputs
outputTextBorderHeaderFooter
	 "Generated on 13. Juni 2021 um 18:14:31"

	^'Report
page width: 792
page height: 612
margin: #(36 36 36 36)
layout: 36 756 576 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 2
---
page width: 792
page height: 612
maximum Y: 563.645 (page height - footer)
output parts: 7
#(10 0 0 -10 36 572.378) This is a footer
#(10 0 0 -10 36 44.7325) This is a header
35.95 @ 58.355 line: 756.05 @ 58.355 0.1
756 @ 58.355 line: 756 @ 72.71 0.1
35.95 @ 72.71 line: 756.05 @ 72.71 0.1
36 @ 72.71 line: 36 @ 58.355 0.1
#(10 0 0 -10 38 69.0875) This is a string on the page
---
page width: 792
page height: 612
maximum Y: 563.645 (page height - footer)
output parts: 3
#(10 0 0 -10 36 572.378) This is a 2nd page footer
#(10 0 0 -10 36 44.7325) This is a 2nd page header
#(10 0 0 -10 36 57.0875) This is a string on the second page'
