outputs
outputTextWithCopyrightTrademark
	 "Generated on 13. Juni 2021 um 18:14:37"

	^'Report
page width: 612
page height: 792
margin: #(36 36 36 36)
layout: 36 576 756 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 792
maximum Y: 756 (page height - footer)
output parts: 3
#(10 0 0 -10 36 44.7325) Copyright ©
#(10 0 0 -10 36 57.0875) Trademark ®
#(10 0 0 -10 36 69.4425) Copyright©, Trademark®'
