outputs
outputTextBorder
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 612
page height: 792
margin: #(36 36 36 36)
layout: 36 576 756 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 792
maximum Y: 718.935 (page height - footer)
output parts: 38
#(10 0 0 -10 36 727.667) This is a footer with default formatting. Footers are printed bottom up
#(20 0 0 -20 36 748.755) This is a footer
#(20 0 0 -20 36 53.465) This is a header
#(10 0 0 -10 36 69.4425) This is a second header section with default formatting
45.5 @ 83.065 line: 566.5 @ 83.065 1
566 @ 83.065 line: 566 @ 142.485 1
45.5 @ 142.485 line: 566.5 @ 142.485 1
46 @ 142.485 line: 46 @ 83.065 1
#(10 0 0 -10 51 96.7975) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable 
#(10 0 0 -10 51 109.152) Document Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise 
#(10 0 0 -10 51 121.507) Content Management Association (AIIM), for the purpose of publication by the International Organization for 
#(10 0 0 -10 51 133.862) Standardization (ISO).
#(12 0 0 -12 56 182.964) PDF has become a de facto global standard for more secure and dependable information 
#(12 0 0 -12 56 197.79) exchange since Adobe published the complete PDF specification in 1993. Both government 
#(12 0 0 -12 56 212.616) and private industry have come to rely on PDF for the volumes of electronic records 
#(12 0 0 -12 56 227.442) that need to be more securely and reliably shared, managed, and in some cases preserved 
#(12 0 0 -12 56 242.268) for generations. Since 1995 Adobe has participated in various working groups that 
#(12 0 0 -12 56 257.094) develop technical specifications for publication by ISO and worked within the ISO 
#(12 0 0 -12 56 271.92) process to deliver specialized subsets of PDF as standards for specific industries and 
#(12 0 0 -12 56 286.746) functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO 
#(12 0 0 -12 56 301.572) standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are 
#(12 0 0 -12 56 316.398) proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best 
#(12 0 0 -12 56 331.224) Practice Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.
65.0 @ 385.571 line: 547.0 @ 385.571 2
546 @ 385.571 line: 546 @ 526.65 2
65.0 @ 526.65 line: 547.0 @ 526.65 2
66 @ 526.65 line: 66 @ 385.571 2
#(14 0 0 -14 76 407.796) In the spring of 2008 the ISO 32000 document was prepared by Adobe 
#(14 0 0 -14 76 425.093) Systems Incorporated (based upon PDF Reference, sixth edition, 
#(14 0 0 -14 76 442.39) Adobe Portable Document Format version 1.7, November 2006) and was 
#(14 0 0 -14 76 459.687) reviewed, edited and adopted, under a special "fast-track 
#(14 0 0 -14 76 476.984) procedure", by Technical Committee ISO/TC 171, Document management 
#(14 0 0 -14 76 494.281) application, Subcommittee SC 2, Application issues, in parallel with 
#(14 0 0 -14 76 511.578) its approval by the ISO member bodies.
#(16 0 0 -16 76 610.622) In January 2008, this ISO technical committee approved the 
#(16 0 0 -16 76 630.39) final revised documentation for PDF 1.7 as the international 
#(16 0 0 -16 76 650.158) standard ISO 32000-1. In July 2008 the ISO document was 
#(16 0 0 -16 76 669.926) placed for sale on the ISO web site (http://www.iso.org).'
