outputs
outputLayoutPageString
	 "Generated on 13. Juni 2021 um 18:14:37"

	^'Report
page width: 300
page height: 200
margin: #(0 0 0 0)
layout: 0 300 200 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 300
page height: 200
maximum Y: 200 (page height - footer)
output parts: 1
#(10 0 0 -10 0 8.7325) default text'
