outputs
outputBusinessCardText1Border
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 131.645 (page height - footer)
output parts: 14
#(10 0 0 -10 0 140.377) This is a footer
#(10 0 0 -10 0 8.7325) This is a header
9.95 @ 17.355 line: 242.05 @ 17.355 0.1
242 @ 17.355 line: 242 @ 116.195 0.1
9.95 @ 116.195 line: 242.05 @ 116.195 0.1
10 @ 116.195 line: 10 @ 17.355 0.1
#(10 0 0 -10 10 26.0875) On January 29, 2007, Adobe Systems Incorporated 
#(10 0 0 -10 10 38.4425) announced it''s intention to release the full 
#(10 0 0 -10 10 50.7975) Portable Document Format (PDF) 1.7 
#(10 0 0 -10 10 63.1525) specification to the American National Standard 
#(10 0 0 -10 10 75.5075) Institute (ANSI) and the Enterprise Content 
#(10 0 0 -10 10 87.8625) Management Association (AIIM), for the purpose 
#(10 0 0 -10 10 100.217) of publication by the International Organization 
#(10 0 0 -10 10 112.572) for Standardization (ISO).'
