outputs
outputHeaderFooter
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 106.935 (page height - footer)
output parts: 4
#(10 0 0 -10 0 115.667) This is a footer with default formatting (2nd last footer)
#(20 0 0 -20 0 136.755) Bottom most footer. jgyp
#(20 0 0 -20 0 17.465) Top most header
#(10 0 0 -10 0 33.4425) This is a second header section with default formatting'
