outputs
outputTextLong
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 612
page height: 200
margin: #(0 0 0 0)
layout: 0 612 200 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 15
''next page'' size: 4
24.75 @ 25 line: 587.25 @ 25 0.5
587 @ 25 line: 587 @ 175 0.5
24.75 @ 175 line: 587.25 @ 175 0.5
25 @ 175 line: 25 @ 25 0.5
#(10 0 0 -10 30 38.7325) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document 
#(10 0 0 -10 30 51.0875) Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content 
#(10 0 0 -10 30 63.4425) Management Association (AIIM), for the purpose of publication by the International Organization for Standardization 
#(10 0 0 -10 30 75.7975) (ISO).PDF has become a de facto global standard for more secure and dependable information exchange since Adobe 
#(10 0 0 -10 30 88.1525) published the complete PDF specification in 1993. Both government and private industry have come to rely on PDF for 
#(10 0 0 -10 30 100.507) the volumes of electronic records that need to be more securely and reliably shared, managed, and in some cases 
#(10 0 0 -10 30 112.862) preserved for generations. Since 1995 Adobe has participated in various working groups that develop technical 
#(10 0 0 -10 30 125.217) specifications for publication by ISO and worked within the ISO process to deliver specialized subsets of PDF as 
#(10 0 0 -10 30 137.572) standards for specific industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO 
#(10 0 0 -10 30 149.927) standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed standards. 
#(10 0 0 -10 30 162.282) Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM serves as the administrator 
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 15
''next page'' size: 3
24.75 @ 25.5175 line: 587.25 @ 25.5175 0.5
587 @ 25.5175 line: 587 @ 175 0.5
24.75 @ 175 line: 587.25 @ 175 0.5
25 @ 175 line: 25 @ 25.5175 0.5
#(10 0 0 -10 30 39.25) for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems 
#(10 0 0 -10 30 51.605) Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format version 1.7, November 2006) 
#(10 0 0 -10 30 63.96) and was reviewed, edited and adopted, under a special "fast-track procedure", by Technical Committee ISO/TC 171, 
#(10 0 0 -10 30 76.315) Document management application, Subcommittee SC 2, Application issues, in parallel with its approval by the ISO 
#(10 0 0 -10 30 88.67) member bodies.In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as 
#(10 0 0 -10 30 101.025) the international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site 
#(10 0 0 -10 30 113.38) (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full 
#(10 0 0 -10 30 125.735) Portable Document Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the 
#(10 0 0 -10 30 138.09) Enterprise Content Management Association (AIIM), for the purpose of publication by the International Organization 
#(10 0 0 -10 30 150.445) for Standardization (ISO).PDF has become a de facto global standard for more secure and dependable information 
#(10 0 0 -10 30 162.8) exchange since Adobe published the complete PDF specification in 1993. Both government and private industry have 
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 15
''next page'' size: 2
24.75 @ 25.5175 line: 587.25 @ 25.5175 0.5
587 @ 25.5175 line: 587 @ 175 0.5
24.75 @ 175 line: 587.25 @ 175 0.5
25 @ 175 line: 25 @ 25.5175 0.5
#(10 0 0 -10 30 39.25) come to rely on PDF for the volumes of electronic records that need to be more securely and reliably shared, 
#(10 0 0 -10 30 51.605) managed, and in some cases preserved for generations. Since 1995 Adobe has participated in various working groups 
#(10 0 0 -10 30 63.96) that develop technical specifications for publication by ISO and worked within the ISO process to deliver 
#(10 0 0 -10 30 76.315) specialized subsets of PDF as standards for specific industries and functions. Today, PDF for Archive (PDF/A) and 
#(10 0 0 -10 30 88.67) PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) 
#(10 0 0 -10 30 101.025) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM 
#(10 0 0 -10 30 113.38) serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was 
#(10 0 0 -10 30 125.735) prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format 
#(10 0 0 -10 30 138.09) version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track procedure", by 
#(10 0 0 -10 30 150.445) Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in parallel 
#(10 0 0 -10 30 162.8) with its approval by the ISO member bodies.In January 2008, this ISO technical committee approved the final revised 
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 15
''next page'' size: 1
24.75 @ 25.5175 line: 587.25 @ 25.5175 0.5
587 @ 25.5175 line: 587 @ 175 0.5
24.75 @ 175 line: 587.25 @ 175 0.5
25 @ 175 line: 25 @ 25.5175 0.5
#(10 0 0 -10 30 39.25) documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document was placed for 
#(10 0 0 -10 30 51.605) sale on the ISO web site (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s 
#(10 0 0 -10 30 63.96) intention to release the full Portable Document Format (PDF) 1.7 specification to the American National Standard 
#(10 0 0 -10 30 76.315) Institute (ANSI) and the Enterprise Content Management Association (AIIM), for the purpose of publication by the 
#(10 0 0 -10 30 88.67) International Organization for Standardization (ISO).PDF has become a de facto global standard for more secure and 
#(10 0 0 -10 30 101.025) dependable information exchange since Adobe published the complete PDF specification in 1993. Both government and 
#(10 0 0 -10 30 113.38) private industry have come to rely on PDF for the volumes of electronic records that need to be more securely and 
#(10 0 0 -10 30 125.735) reliably shared, managed, and in some cases preserved for generations. Since 1995 Adobe has participated in various 
#(10 0 0 -10 30 138.09) working groups that develop technical specifications for publication by ISO and worked within the ISO process to 
#(10 0 0 -10 30 150.445) deliver specialized subsets of PDF as standards for specific industries and functions. Today, PDF for Archive 
#(10 0 0 -10 30 162.8) (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal 
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 12
24.75 @ 25.5175 line: 587.25 @ 25.5175 0.5
587 @ 25.5175 line: 587 @ 175 0.5
24.75 @ 175 line: 587.25 @ 175 0.5
25 @ 175 line: 25 @ 25.5175 0.5
#(10 0 0 -10 30 39.25) Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice 
#(10 0 0 -10 30 51.605) Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 
#(10 0 0 -10 30 63.96) document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable 
#(10 0 0 -10 30 76.315) Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track 
#(10 0 0 -10 30 88.67) procedure", by Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application 
#(10 0 0 -10 30 101.025) issues, in parallel with its approval by the ISO member bodies.In January 2008, this ISO technical committee approved 
#(10 0 0 -10 30 113.38) the final revised documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document 
#(10 0 0 -10 30 125.735) was placed for sale on the ISO web site (http://www.iso.org).'
