outputs
outputBackgroundForegroundColor
	 "Generated on 13. Juni 2021 um 18:14:37"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 29
top: 0	bottom: 12.355	width: 252	height: 12.355	color: (ColorValue brightness: 0.800024)
top: 0	bottom: 12.355	width: 252	height: 12.355	color: (ColorValue brightness: 0.800024)
#(10 0 0 -10 0 8.7325) section gray background, red text
top: 0	bottom: 24.71	width: 252	height: 12.355	color: (ColorValue red: 0.749969 green: 0.0 blue: 0.0)
top: 0	bottom: 24.71	width: 252	height: 12.355	color: (ColorValue red: 0.749969 green: 0.0 blue: 0.0)
#(10 0 0 -10 0 21.0875) section red background, grey text
top: 0	bottom: 37.065	width: 252	height: 12.355	color: (ColorValue brightness: 0.900012)
top: 0	bottom: 37.065	width: 252	height: 12.355	color: (ColorValue brightness: 0.900012)
#(10 0 0 -10 0 33.4425) section gray1 background, text gray9 foreground
top: 0	bottom: 49.42	width: 252	height: 12.355	color: (ColorValue brightness: 0.849957)
top: 0	bottom: 49.42	width: 252	height: 12.355	color: (ColorValue brightness: 0.849957)
#(10 0 0 -10 0 45.7975) section gray2 background, text gray8 foreground
top: 0	bottom: 61.775	width: 252	height: 12.355	color: (ColorValue brightness: 0.800024)
top: 0	bottom: 61.775	width: 252	height: 12.355	color: (ColorValue brightness: 0.800024)
#(10 0 0 -10 0 58.1525) section gray3 background, text gray7 foreground
top: 0	bottom: 74.13	width: 252	height: 12.355	color: (ColorValue brightness: 0.700037)
top: 0	bottom: 74.13	width: 252	height: 12.355	color: (ColorValue brightness: 0.700037)
#(10 0 0 -10 0 70.5075) section gray4 background, text gray6 foreground
top: 0	bottom: 86.485	width: 252	height: 12.355	color: (ColorValue brightness: 0.600049)
top: 0	bottom: 86.485	width: 252	height: 12.355	color: (ColorValue brightness: 0.600049)
#(10 0 0 -10 0 82.8625) section gray5 background, text gray5 foreground
top: 0	bottom: 98.84	width: 252	height: 12.355	color: ColorValue gray
#(10 0 0 -10 0 95.2175) text gray6 background, text gray4 foreground
top: 0	bottom: 111.195	width: 252	height: 12.355	color: (ColorValue brightness: 0.399951)
#(10 0 0 -10 0 107.572) text gray7 background, text gray3 foreground
top: 0	bottom: 123.55	width: 252	height: 12.355	color: (ColorValue brightness: 0.299963)
#(10 0 0 -10 0 119.927) text gray8 background, text gray2 foreground
top: 0	bottom: 135.905	width: 252	height: 12.355	color: (ColorValue brightness: 0.199976)
#(10 0 0 -10 0 132.282) text gray9 background, text gray1 foreground'
