outputs
outputString
	 "Generated on 13. Juni 2021 um 18:14:37"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 4
#(10 0 0 -10 0 8.7325) Simple string
#(10 0 0 -10 0 21.0875) Text string
#(12 0 0 -12 0 35.189) String font size 12
#(14 0 0 -14 0 51.7615) Text font size 14'
