outputs
outputTextCheckWrapping
	 "Generated on 13. Juni 2021 um 18:14:37"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 7
#(10 0 0 -10 0 8.7325) Long text that will be wrapped 
#(10 0 0 -10 (13507 / 100) 8.7325) and is followed by text 
#(10 0 0 -10 0 8.7325) 
#(10 0 0 -10 0 21.0875) on a new line after this sentence is finished, but 
#(10 0 0 -10 0 33.4425) there are no line breaks in this sentence.
#(10 0 0 -10 0 45.7975) This text should be on a new line. 
#(10 0 0 -10 0 58.1525) As should this text.'
