outputs
outputText2Border
	 "Generated on 13. Juni 2021 um 18:14:35"

	^'Report
page width: 612
page height: 792
margin: #(36 36 36 36)
layout: 36 576 756 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 792
maximum Y: 756 (page height - footer)
output parts: 15
55.5 @ 56 line: 556.5 @ 56 1
556 @ 56 line: 556 @ 241.905 1
55.5 @ 241.905 line: 556.5 @ 241.905 1
56 @ 241.905 line: 56 @ 56 1
#(10 0 0 -10 86 94.7325) PDF has become a de facto global standard for more secure and dependable information 
#(10 0 0 -10 86 107.087) exchange since Adobe published the complete PDF specification in 1993. Both government and 
#(10 0 0 -10 86 119.442) private industry have come to rely on PDF for the volumes of electronic records that need to 
#(10 0 0 -10 86 131.797) be more securely and reliably shared, managed, and in some cases preserved for generations. 
#(10 0 0 -10 86 144.152) Since 1995 Adobe has participated in various working groups that develop technical 
#(10 0 0 -10 86 156.507) specifications for publication by ISO and worked within the ISO process to deliver 
#(10 0 0 -10 86 168.862) specialized subsets of PDF as standards for specific industries and functions. Today, PDF 
#(10 0 0 -10 86 181.217) for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for 
#(10 0 0 -10 86 193.572) Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed standards. 
#(10 0 0 -10 86 205.927) Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM 
#(10 0 0 -10 86 218.282) serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.'
