outputs
outputTextMultiLineString
	 "Generated on 13. Juni 2021 um 18:14:31"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 7
#(10 0 0 -10 0 8.7325) Text is entered with multiple lines
#(10 0 0 -10 0 21.0875) This
#(10 0 0 -10 0 33.4425) is a
#(10 0 0 -10 0 45.7975) multi-line
#(10 0 0 -10 0 58.1525) string.
#(10 0 0 -10 0 70.5075) It should render as
#(10 0 0 -10 0 82.8625) six lines of text.'
