outputs
outputText1Border
	 "Generated on 13. Juni 2021 um 18:14:35"

	^'Report
page width: 612
page height: 792
margin: #(36 36 36 36)
layout: 36 576 756 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 792
maximum Y: 743.645 (page height - footer)
output parts: 10
#(10 0 0 -10 36 752.378) This is a footer
#(10 0 0 -10 36 44.7325) This is a header
75.5 @ 68.355 line: 556.5 @ 68.355 1
556 @ 68.355 line: 556 @ 122.775 1
75.5 @ 122.775 line: 556.5 @ 122.775 1
76 @ 122.775 line: 76 @ 68.355 1
#(10 0 0 -10 81 82.0875) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full 
#(10 0 0 -10 81 94.4425) Portable Document Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) 
#(10 0 0 -10 81 106.797) and the Enterprise Content Management Association (AIIM), for the purpose of publication by the 
#(10 0 0 -10 81 119.152) International Organization for Standardization (ISO).'
