outputs
outputTextMultiplePages
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 612
page height: 200
margin: #(0 0 0 0)
layout: 0 612 200 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 4
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 4
#(20 0 0 -20 0 17.465) Page 1 of 4
#(10 0 0 -10 10 43.4425) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document Format (PDF) 1.7 
#(10 0 0 -10 10 55.7975) specification to the American National Standard Institute (ANSI) and the Enterprise Content Management Association (AIIM), for 
#(10 0 0 -10 10 68.1525) the purpose of publication by the International Organization for Standardization (ISO).
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 9
#(20 0 0 -20 0 17.465) Page 2 of 4
#(10 0 0 -10 10 43.4425) PDF has become a de facto global standard for more secure and dependable information exchange since Adobe published the 
#(10 0 0 -10 10 55.7975) complete PDF specification in 1993. Both government and private industry have come to rely on PDF for the volumes of 
#(10 0 0 -10 10 68.1525) electronic records that need to be more securely and reliably shared, managed, and in some cases preserved for generations. 
#(10 0 0 -10 10 80.5075) Since 1995 Adobe has participated in various working groups that develop technical specifications for publication by ISO and 
#(10 0 0 -10 10 92.8625) worked within the ISO process to deliver specialized subsets of PDF as standards for specific industries and functions. 
#(10 0 0 -10 10 105.217) Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for 
#(10 0 0 -10 10 117.572) Universal Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best 
#(10 0 0 -10 10 129.927) Practice Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 5
#(20 0 0 -20 0 17.465) Page 3 of 4
#(10 0 0 -10 10 43.4425) In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth 
#(10 0 0 -10 10 55.7975) edition, Adobe Portable Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special 
#(10 0 0 -10 10 68.1525) "fast-track procedure", by Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application 
#(10 0 0 -10 10 80.5075) issues, in parallel with its approval by the ISO member bodies.
---
page width: 612
page height: 200
maximum Y: 200 (page height - footer)
output parts: 3
#(20 0 0 -20 0 17.465) Page 4 of 4
#(10 0 0 -10 10 43.4425) In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as the international standard 
#(10 0 0 -10 10 55.7975) ISO 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site (http://www.iso.org).'
