accessing
sampleText3
	
	^'In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track procedure", by Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in parallel with its approval by the ISO member bodies.'
