outputs
outputImageJPG
	 "Generated on 13. Juni 2021 um 18:14:35"

	^'Report
page width: 792
page height: 612
margin: #(36 36 36 36)
layout: 36 756 576 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 792
page height: 612
maximum Y: 576 (page height - footer)
output parts: 6
#(10 0 0 -10 36 44.7325) Show large JPG image, with border
#(546.0 0 0 -122.25 37 171.605) [image] 
35.5 @ 48.355 line: 584.5 @ 48.355 1
584.0 @ 48.355 line: 584.0 @ 171.605 1
35.5 @ 171.605 line: 584.5 @ 171.605 1
36 @ 171.605 line: 36 @ 48.355 1'
