outputs
outputImageJPGPageBreak
	 "Generated on 13. Juni 2021 um 18:14:32"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 142 (page height - footer)
output parts: 8
''next page'' size: 1
#(10 0 0 -10 2 8.7325) Image will be displayed on the next page
#(10 0 0 -10 2 21.0875) because of there is not enough room on the first page
#(10 0 0 -10 2 33.4425) with
#(10 0 0 -10 2 45.7975) this
#(10 0 0 -10 2 58.1525) much
#(10 0 0 -10 2 70.5075) text
#(10 0 0 -10 2 82.8625) on
#(10 0 0 -10 2 95.2175) top.
---
page width: 252
page height: 144
maximum Y: 142 (page height - footer)
output parts: 5
#(248.0 0 0 -55.5275 2 61.5275) [image] 
1.5 @ 6 line: 250.5 @ 6 1
250.0 @ 6 line: 250.0 @ 61.5275 1
1.5 @ 61.5275 line: 250.5 @ 61.5275 1
2 @ 61.5275 line: 2 @ 6 1'
