outputs
outputTextLongReportMargins
	 "Generated on 13. Juni 2021 um 18:14:33"

	^'Report
page width: 612
page height: 200
margin: #(10 10 10 10)
layout: 10 602 190 10
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 200
maximum Y: 175.174 (page height - footer)
output parts: 10
''next page'' size: 7
#(12 0 0 -12 10 185.653) This is a footer
#(12 0 0 -12 10 20.479) This text will span multiple pages. Page number: 1 of 8
#(10 0 0 -10 10 33.5585) This header should only be visible on page 1
#(10 0 0 -10 30 65.9135) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document 
#(10 0 0 -10 30 78.2685) Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content 
#(10 0 0 -10 30 90.6235) Management Association (AIIM), for the purpose of publication by the International Organization for Standardization 
#(10 0 0 -10 30 102.978) (ISO).PDF has become a de facto global standard for more secure and dependable information exchange since Adobe 
#(10 0 0 -10 30 115.333) published the complete PDF specification in 1993. Both government and private industry have come to rely on PDF for 
#(10 0 0 -10 30 127.688) the volumes of electronic records that need to be more securely and reliably shared, managed, and in some cases 
#(10 0 0 -10 30 140.043) preserved for generations. Since 1995 Adobe has participated in various working groups that develop technical 
---
page width: 612
page height: 200
maximum Y: 162.819 (page height - footer)
output parts: 10
''next page'' size: 6
#(12 0 0 -12 10 173.298) This is a footer
#(10 0 0 -10 10 186.378) This footer should only be visible after page 1
#(12 0 0 -12 10 20.479) This text will span multiple pages. Page number: 2 of 8
#(10 0 0 -10 30 54.076) specifications for publication by ISO and worked within the ISO process to deliver specialized subsets of PDF as 
#(10 0 0 -10 30 66.431) standards for specific industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO 
#(10 0 0 -10 30 78.786) standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed standards. 
#(10 0 0 -10 30 91.141) Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM serves as the administrator 
#(10 0 0 -10 30 103.496) for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems 
#(10 0 0 -10 30 115.851) Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format version 1.7, November 2006) 
#(10 0 0 -10 30 128.206) and was reviewed, edited and adopted, under a special "fast-track procedure", by Technical Committee ISO/TC 171, 
---
page width: 612
page height: 200
maximum Y: 162.819 (page height - footer)
output parts: 10
''next page'' size: 5
#(12 0 0 -12 10 173.298) This is a footer
#(10 0 0 -10 10 186.378) This footer should only be visible after page 1
#(12 0 0 -12 10 20.479) This text will span multiple pages. Page number: 3 of 8
#(10 0 0 -10 30 54.076) Document management application, Subcommittee SC 2, Application issues, in parallel with its approval by the ISO 
#(10 0 0 -10 30 66.431) member bodies.In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as 
#(10 0 0 -10 30 78.786) the international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site 
#(10 0 0 -10 30 91.141) (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full 
#(10 0 0 -10 30 103.496) Portable Document Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the 
#(10 0 0 -10 30 115.851) Enterprise Content Management Association (AIIM), for the purpose of publication by the International Organization 
#(10 0 0 -10 30 128.206) for Standardization (ISO).PDF has become a de facto global standard for more secure and dependable information 
---
page width: 612
page height: 200
maximum Y: 162.819 (page height - footer)
output parts: 10
''next page'' size: 4
#(12 0 0 -12 10 173.298) This is a footer
#(10 0 0 -10 10 186.378) This footer should only be visible after page 1
#(12 0 0 -12 10 20.479) This text will span multiple pages. Page number: 4 of 8
#(10 0 0 -10 30 54.076) exchange since Adobe published the complete PDF specification in 1993. Both government and private industry have 
#(10 0 0 -10 30 66.431) come to rely on PDF for the volumes of electronic records that need to be more securely and reliably shared, 
#(10 0 0 -10 30 78.786) managed, and in some cases preserved for generations. Since 1995 Adobe has participated in various working groups 
#(10 0 0 -10 30 91.141) that develop technical specifications for publication by ISO and worked within the ISO process to deliver 
#(10 0 0 -10 30 103.496) specialized subsets of PDF as standards for specific industries and functions. Today, PDF for Archive (PDF/A) and 
#(10 0 0 -10 30 115.851) PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) 
#(10 0 0 -10 30 128.206) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM 
---
page width: 612
page height: 200
maximum Y: 162.819 (page height - footer)
output parts: 10
''next page'' size: 3
#(12 0 0 -12 10 173.298) This is a footer
#(10 0 0 -10 10 186.378) This footer should only be visible after page 1
#(12 0 0 -12 10 20.479) This text will span multiple pages. Page number: 5 of 8
#(10 0 0 -10 30 54.076) serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was 
#(10 0 0 -10 30 66.431) prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format 
#(10 0 0 -10 30 78.786) version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track procedure", by 
#(10 0 0 -10 30 91.141) Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in parallel 
#(10 0 0 -10 30 103.496) with its approval by the ISO member bodies.In January 2008, this ISO technical committee approved the final revised 
#(10 0 0 -10 30 115.851) documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document was placed for 
#(10 0 0 -10 30 128.206) sale on the ISO web site (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s 
---
page width: 612
page height: 200
maximum Y: 162.819 (page height - footer)
output parts: 10
''next page'' size: 2
#(12 0 0 -12 10 173.298) This is a footer
#(10 0 0 -10 10 186.378) This footer should only be visible after page 1
#(12 0 0 -12 10 20.479) This text will span multiple pages. Page number: 6 of 8
#(10 0 0 -10 30 54.076) intention to release the full Portable Document Format (PDF) 1.7 specification to the American National Standard 
#(10 0 0 -10 30 66.431) Institute (ANSI) and the Enterprise Content Management Association (AIIM), for the purpose of publication by the 
#(10 0 0 -10 30 78.786) International Organization for Standardization (ISO).PDF has become a de facto global standard for more secure and 
#(10 0 0 -10 30 91.141) dependable information exchange since Adobe published the complete PDF specification in 1993. Both government and 
#(10 0 0 -10 30 103.496) private industry have come to rely on PDF for the volumes of electronic records that need to be more securely and 
#(10 0 0 -10 30 115.851) reliably shared, managed, and in some cases preserved for generations. Since 1995 Adobe has participated in various 
#(10 0 0 -10 30 128.206) working groups that develop technical specifications for publication by ISO and worked within the ISO process to 
---
page width: 612
page height: 200
maximum Y: 162.819 (page height - footer)
output parts: 10
''next page'' size: 1
#(12 0 0 -12 10 173.298) This is a footer
#(10 0 0 -10 10 186.378) This footer should only be visible after page 1
#(12 0 0 -12 10 20.479) This text will span multiple pages. Page number: 7 of 8
#(10 0 0 -10 30 54.076) deliver specialized subsets of PDF as standards for specific industries and functions. Today, PDF for Archive 
#(10 0 0 -10 30 66.431) (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal 
#(10 0 0 -10 30 78.786) Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice 
#(10 0 0 -10 30 91.141) Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 
#(10 0 0 -10 30 103.496) document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable 
#(10 0 0 -10 30 115.851) Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track 
#(10 0 0 -10 30 128.206) procedure", by Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application 
---
page width: 612
page height: 200
maximum Y: 162.819 (page height - footer)
output parts: 6
#(12 0 0 -12 10 173.298) This is a footer
#(10 0 0 -10 10 186.378) This footer should only be visible after page 1
#(12 0 0 -12 10 20.479) This text will span multiple pages. Page number: 8 of 8
#(10 0 0 -10 30 54.076) issues, in parallel with its approval by the ISO member bodies.In January 2008, this ISO technical committee approved 
#(10 0 0 -10 30 66.431) the final revised documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document 
#(10 0 0 -10 30 78.786) was placed for sale on the ISO web site (http://www.iso.org).'
