outputs
outputBackgroundColor
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 2
top: 0	bottom: 12.355	width: 252	height: 12.355	color: (ColorValue brightness: 0.800024)
#(10 0 0 -10 0 8.7325) gray background'
