outputs
outputTextWithLines
	 "Generated on 13. Juni 2021 um 18:14:31"

	^'Report
page width: 792
page height: 612
margin: #(36 36 36 36)
layout: 36 756 576 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 792
page height: 612
maximum Y: 551.29 (page height - footer)
output parts: 27
#(20 0 0 -20 36 568.755) This is a footer
#(20 0 0 -20 36 53.465) This is a header
36 @ 64.71 line: 756 @ 64.71 0.5
#(10 0 0 -10 46 87.4425) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document Format (PDF) 1.7 specification to the 
#(10 0 0 -10 46 99.7975) American National Standard Institute (ANSI) and the Enterprise Content Management Association (AIIM), for the purpose of publication by the 
#(10 0 0 -10 46 112.152) International Organization for Standardization (ISO).
36 @ 129.775 line: 756 @ 129.775 0.5
#(10 0 0 -10 56 162.507) PDF has become a de facto global standard for more secure and dependable information exchange since Adobe published the complete PDF 
#(10 0 0 -10 56 174.862) specification in 1993. Both government and private industry have come to rely on PDF for the volumes of electronic records that need to be more 
#(10 0 0 -10 56 187.217) securely and reliably shared, managed, and in some cases preserved for generations. Since 1995 Adobe has participated in various working groups 
#(10 0 0 -10 56 199.572) that develop technical specifications for publication by ISO and worked within the ISO process to deliver specialized subsets of PDF as 
#(10 0 0 -10 56 211.927) standards for specific industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for 
#(10 0 0 -10 56 224.282) Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM 
#(10 0 0 -10 56 236.637) proposed Best Practice Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.
36 @ 264.26 line: 756 @ 264.26 0.5
65.5 @ 298.26 line: 726.5 @ 298.26 1
726 @ 298.26 line: 726 @ 357.68 1
65.5 @ 357.68 line: 726.5 @ 357.68 1
66 @ 357.68 line: 66 @ 298.26 1
#(10 0 0 -10 71 311.992) In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe 
#(10 0 0 -10 71 324.347) Portable Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track procedure", by 
#(10 0 0 -10 71 336.702) Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in parallel with its approval 
#(10 0 0 -10 71 349.057) by the ISO member bodies.
76 @ 401.68 line: 716 @ 401.68 0.5
#(10 0 0 -10 76 414.412) In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as the international standard ISO 
#(10 0 0 -10 76 426.767) 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site (http://www.iso.org).
76 @ 434.39 line: 716 @ 434.39 0.5'
