outputs
outputTextFlip
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 612
page height: 792
margin: #(36 36 36 36)
layout: 36 576 756 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 792
maximum Y: 718.935 (page height - footer)
output parts: 31
#(-20 0 0 20 576 717.9) This is a footer
#(10 0 0 -10 36 752.378) This is a footer with default formatting. Footers are printed bottom up
#(20 0 0 -20 36 53.465) This is a header
#(10 0 0 -10 36 69.4425) This is a second header section with default formatting
#(-10 0 0 10 566 82.5475) Standardization (ISO).
#(-10 0 0 10 566 94.9025) Management Association (AIIM), for the purpose of publication by the International Organization for 
#(-10 0 0 10 566 107.257) Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content 
#(-10 0 0 10 566 119.612) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document 
#(12 0 0 -12 56 172.964) PDF has become a de facto global standard for more secure and dependable information 
#(12 0 0 -12 56 187.79) exchange since Adobe published the complete PDF specification in 1993. Both government 
#(12 0 0 -12 56 202.616) and private industry have come to rely on PDF for the volumes of electronic records 
#(12 0 0 -12 56 217.442) that need to be more securely and reliably shared, managed, and in some cases preserved 
#(12 0 0 -12 56 232.268) for generations. Since 1995 Adobe has participated in various working groups that 
#(12 0 0 -12 56 247.094) develop technical specifications for publication by ISO and worked within the ISO 
#(12 0 0 -12 56 261.92) process to deliver specialized subsets of PDF as standards for specific industries and 
#(12 0 0 -12 56 276.746) functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO 
#(12 0 0 -12 56 291.572) standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are 
#(12 0 0 -12 56 306.398) proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best 
#(12 0 0 -12 56 321.224) Practice Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.
#(-14 0 0 14 546 374.846) the ISO member bodies.
#(-14 0 0 14 546 392.143) Subcommittee SC 2, Application issues, in parallel with its approval by 
#(-14 0 0 14 546 409.44) Technical Committee ISO/TC 171, Document management application, 
#(-14 0 0 14 546 426.737) edited and adopted, under a special "fast-track procedure", by 
#(-14 0 0 14 546 444.034) Portable Document Format version 1.7, November 2006) and was reviewed, 
#(-14 0 0 14 546 461.331) Systems Incorporated (based upon PDF Reference, sixth edition, Adobe 
#(-14 0 0 14 546 478.628) In the spring of 2008 the ISO 32000 document was prepared by Adobe 
#(18 0 0 -18 76 582.368) In January 2008, this ISO technical committee 
#(18 0 0 -18 76 604.607) approved the final revised documentation for PDF 1.7 
#(18 0 0 -18 76 626.846) as the international standard ISO 32000-1. In July 
#(18 0 0 -18 76 649.085) 2008 the ISO document was placed for sale on the ISO 
#(18 0 0 -18 76 671.324) web site (http://www.iso.org).'
