outputs
outputTextLongHeaderFooter
	 "Generated on 13. Juni 2021 um 18:14:32"

	^'Report
page width: 612
page height: 200
margin: #(0 0 0 0)
layout: 0 612 200 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 200
maximum Y: 187.645 (page height - footer)
output parts: 11
''next page'' size: 6
#(10 0 0 -10 0 196.378) This is a footer
#(10 0 0 -10 0 8.7325) This text will span multiple pages. Page number: 1
#(10 0 0 -10 0 21.0875) This header should only be visible on page 1
#(10 0 0 -10 30 63.4425) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document 
#(10 0 0 -10 30 75.7975) Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content 
#(10 0 0 -10 30 88.1525) Management Association (AIIM), for the purpose of publication by the International Organization for Standardization 
#(10 0 0 -10 30 100.507) (ISO).PDF has become a de facto global standard for more secure and dependable information exchange since Adobe 
#(10 0 0 -10 30 112.862) published the complete PDF specification in 1993. Both government and private industry have come to rely on PDF for 
#(10 0 0 -10 30 125.217) the volumes of electronic records that need to be more securely and reliably shared, managed, and in some cases 
#(10 0 0 -10 30 137.572) preserved for generations. Since 1995 Adobe has participated in various working groups that develop technical 
#(10 0 0 -10 30 149.927) specifications for publication by ISO and worked within the ISO process to deliver specialized subsets of PDF as 
---
page width: 612
page height: 200
maximum Y: 175.29 (page height - footer)
output parts: 11
''next page'' size: 5
#(10 0 0 -10 0 184.023) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(10 0 0 -10 0 8.7325) This text will span multiple pages. Page number: 2
#(10 0 0 -10 30 51.605) standards for specific industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO 
#(10 0 0 -10 30 63.96) standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed standards. 
#(10 0 0 -10 30 76.315) Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM serves as the administrator 
#(10 0 0 -10 30 88.67) for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems 
#(10 0 0 -10 30 101.025) Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format version 1.7, November 2006) 
#(10 0 0 -10 30 113.38) and was reviewed, edited and adopted, under a special "fast-track procedure", by Technical Committee ISO/TC 171, 
#(10 0 0 -10 30 125.735) Document management application, Subcommittee SC 2, Application issues, in parallel with its approval by the ISO 
#(10 0 0 -10 30 138.09) member bodies.In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as 
---
page width: 612
page height: 200
maximum Y: 175.29 (page height - footer)
output parts: 11
''next page'' size: 4
#(10 0 0 -10 0 184.023) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(10 0 0 -10 0 8.7325) This text will span multiple pages. Page number: 3
#(10 0 0 -10 30 51.605) the international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site 
#(10 0 0 -10 30 63.96) (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full 
#(10 0 0 -10 30 76.315) Portable Document Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the 
#(10 0 0 -10 30 88.67) Enterprise Content Management Association (AIIM), for the purpose of publication by the International Organization 
#(10 0 0 -10 30 101.025) for Standardization (ISO).PDF has become a de facto global standard for more secure and dependable information 
#(10 0 0 -10 30 113.38) exchange since Adobe published the complete PDF specification in 1993. Both government and private industry have 
#(10 0 0 -10 30 125.735) come to rely on PDF for the volumes of electronic records that need to be more securely and reliably shared, 
#(10 0 0 -10 30 138.09) managed, and in some cases preserved for generations. Since 1995 Adobe has participated in various working groups 
---
page width: 612
page height: 200
maximum Y: 175.29 (page height - footer)
output parts: 11
''next page'' size: 3
#(10 0 0 -10 0 184.023) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(10 0 0 -10 0 8.7325) This text will span multiple pages. Page number: 4
#(10 0 0 -10 30 51.605) that develop technical specifications for publication by ISO and worked within the ISO process to deliver 
#(10 0 0 -10 30 63.96) specialized subsets of PDF as standards for specific industries and functions. Today, PDF for Archive (PDF/A) and 
#(10 0 0 -10 30 76.315) PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) 
#(10 0 0 -10 30 88.67) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM 
#(10 0 0 -10 30 101.025) serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 document was 
#(10 0 0 -10 30 113.38) prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable Document Format 
#(10 0 0 -10 30 125.735) version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track procedure", by 
#(10 0 0 -10 30 138.09) Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application issues, in parallel 
---
page width: 612
page height: 200
maximum Y: 175.29 (page height - footer)
output parts: 11
''next page'' size: 2
#(10 0 0 -10 0 184.023) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(10 0 0 -10 0 8.7325) This text will span multiple pages. Page number: 5
#(10 0 0 -10 30 51.605) with its approval by the ISO member bodies.In January 2008, this ISO technical committee approved the final revised 
#(10 0 0 -10 30 63.96) documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document was placed for 
#(10 0 0 -10 30 76.315) sale on the ISO web site (http://www.iso.org).On January 29, 2007, Adobe Systems Incorporated announced it''s 
#(10 0 0 -10 30 88.67) intention to release the full Portable Document Format (PDF) 1.7 specification to the American National Standard 
#(10 0 0 -10 30 101.025) Institute (ANSI) and the Enterprise Content Management Association (AIIM), for the purpose of publication by the 
#(10 0 0 -10 30 113.38) International Organization for Standardization (ISO).PDF has become a de facto global standard for more secure and 
#(10 0 0 -10 30 125.735) dependable information exchange since Adobe published the complete PDF specification in 1993. Both government and 
#(10 0 0 -10 30 138.09) private industry have come to rely on PDF for the volumes of electronic records that need to be more securely and 
---
page width: 612
page height: 200
maximum Y: 175.29 (page height - footer)
output parts: 11
''next page'' size: 1
#(10 0 0 -10 0 184.023) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(10 0 0 -10 0 8.7325) This text will span multiple pages. Page number: 6
#(10 0 0 -10 30 51.605) reliably shared, managed, and in some cases preserved for generations. Since 1995 Adobe has participated in various 
#(10 0 0 -10 30 63.96) working groups that develop technical specifications for publication by ISO and worked within the ISO process to 
#(10 0 0 -10 30 76.315) deliver specialized subsets of PDF as standards for specific industries and functions. Today, PDF for Archive 
#(10 0 0 -10 30 88.67) (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal 
#(10 0 0 -10 30 101.025) Access (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice 
#(10 0 0 -10 30 113.38) Guide. AIIM serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.In the spring of 2008 the ISO 32000 
#(10 0 0 -10 30 125.735) document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth edition, Adobe Portable 
#(10 0 0 -10 30 138.09) Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special "fast-track 
---
page width: 612
page height: 200
maximum Y: 175.29 (page height - footer)
output parts: 7
#(10 0 0 -10 0 184.023) This is a footer
#(10 0 0 -10 0 196.378) This footer should only be visible after page 1
#(10 0 0 -10 0 8.7325) This text will span multiple pages. Page number: 7
#(10 0 0 -10 30 51.605) procedure", by Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application 
#(10 0 0 -10 30 63.96) issues, in parallel with its approval by the ISO member bodies.In January 2008, this ISO technical committee approved 
#(10 0 0 -10 30 76.315) the final revised documentation for PDF 1.7 as the international standard ISO 32000-1. In July 2008 the ISO document 
#(10 0 0 -10 30 88.67) was placed for sale on the ISO web site (http://www.iso.org).'
