outputs
outputBusinessCardText2Border
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 13
''next page'' size: 2
9.9 @ 10 line: 242.1 @ 10 0.2
242 @ 10 line: 242 @ 134 0.2
9.9 @ 134 line: 242.1 @ 134 0.2
10 @ 134 line: 10 @ 10 0.2
#(10 0 0 -10 15 23.7325) PDF has become a de facto global standard 
#(10 0 0 -10 15 36.0875) for more secure and dependable information 
#(10 0 0 -10 15 48.4425) exchange since Adobe published the complete 
#(10 0 0 -10 15 60.7975) PDF specification in 1993. Both government 
#(10 0 0 -10 15 73.1525) and private industry have come to rely on 
#(10 0 0 -10 15 85.5075) PDF for the volumes of electronic records 
#(10 0 0 -10 15 97.8625) that need to be more securely and reliably 
#(10 0 0 -10 15 110.217) shared, managed, and in some cases preserved 
#(10 0 0 -10 15 122.572) for generations. Since 1995 Adobe has 
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 13
''next page'' size: 1
9.9 @ 10.5175 line: 242.1 @ 10.5175 0.2
242 @ 10.5175 line: 242 @ 134 0.2
9.9 @ 134 line: 242.1 @ 134 0.2
10 @ 134 line: 10 @ 10.5175 0.2
#(10 0 0 -10 15 24.25) participated in various working groups that 
#(10 0 0 -10 15 36.605) develop technical specifications for 
#(10 0 0 -10 15 48.96) publication by ISO and worked within the ISO 
#(10 0 0 -10 15 61.315) process to deliver specialized subsets of 
#(10 0 0 -10 15 73.67) PDF as standards for specific industries 
#(10 0 0 -10 15 86.025) and functions. Today, PDF for Archive 
#(10 0 0 -10 15 98.38) (PDF/A) and PDF for Exchange (PDF/X) are 
#(10 0 0 -10 15 110.735) ISO standards, and PDF for Engineering 
#(10 0 0 -10 15 123.09) (PDF/E) and PDF for Universal Access 
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 9
9.9 @ 10.5175 line: 242.1 @ 10.5175 0.2
242 @ 10.5175 line: 242 @ 134 0.2
9.9 @ 134 line: 242.1 @ 134 0.2
10 @ 134 line: 10 @ 10.5175 0.2
#(10 0 0 -10 15 24.25) (PDF/UA) are proposed standards. 
#(10 0 0 -10 15 36.605) Additionally, PDF for Healthcare (PDF/H) is 
#(10 0 0 -10 15 48.96) an AIIM proposed Best Practice Guide. AIIM 
#(10 0 0 -10 15 61.315) serves as the administrator for PDF/A, 
#(10 0 0 -10 15 73.67) PDF/E, PDF/UA and PDF/H.'
