outputs
outputImageJPGFixed
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 142 (page height - footer)
output parts: 11
#(10 0 0 -10 2 8.7325) Show JPG and GIF image using fixed layouts
#(110 0 0 -115 10 135) [image] 
9.5 @ 20 line: 120.5 @ 20 1
120 @ 20 line: 120 @ 135 1
9.5 @ 135 line: 120.5 @ 135 1
10 @ 135 line: 10 @ 20 1
#(117 0 0 -115 125 135) [image] 
124.5 @ 20 line: 242.5 @ 20 1
242 @ 20 line: 242 @ 135 1
124.5 @ 135 line: 242.5 @ 135 1
125 @ 135 line: 125 @ 20 1'
