outputs
outputImageJPGScaled
	 "Generated on 13. Juni 2021 um 18:14:32"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 142 (page height - footer)
output parts: 7
#(10 0 0 -10 2 8.7325) Show large JPG image scaled to fit, with border
#(248.0 0 0 -55.5275 2 67.8825) [image] 
1.5 @ 12.355 line: 250.5 @ 12.355 1
250.0 @ 12.355 line: 250.0 @ 67.8825 1
1.5 @ 67.8825 line: 250.5 @ 67.8825 1
2 @ 67.8825 line: 2 @ 12.355 1
#(10 0 0 -10 2 76.615) this is text added to the image'
