outputs
outputTextWithBullets
	 "Generated on 13. Juni 2021 um 18:14:36"

	^'Report
page width: 612
page height: 300
margin: #(36 36 36 36)
layout: 36 576 264 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 612
page height: 300
maximum Y: 264 (page height - footer)
output parts: 21
''next page'' size: 1
#(10 0 0 -10 36 44.7325) Text with bullets
#(6 0 0 -6 36 55.869) l
#(10 0 0 -10 (1089 / 25) 57.0875) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document 
#(10 0 0 -10 (1089 / 25) 69.4425) Format (PDF) 1.7 specification to the American National Standard Institute (ANSI) and the Enterprise Content 
#(10 0 0 -10 (1089 / 25) 81.7975) Management Association (AIIM), for the purpose of publication by the International Organization for Standardization 
#(10 0 0 -10 (1089 / 25) 94.1525) (ISO).
#(6 0 0 -6 36 105.289) l
#(10 0 0 -10 (1089 / 25) 106.507) PDF has become a de facto global standard for more secure and dependable information exchange since Adobe 
#(10 0 0 -10 (1089 / 25) 118.862) published the complete PDF specification in 1993. Both government and private industry have come to rely on PDF 
#(10 0 0 -10 (1089 / 25) 131.217) for the volumes of electronic records that need to be more securely and reliably shared, managed, and in some 
#(10 0 0 -10 (1089 / 25) 143.572) cases preserved for generations. Since 1995 Adobe has participated in various working groups that develop 
#(10 0 0 -10 (1089 / 25) 155.927) technical specifications for publication by ISO and worked within the ISO process to deliver specialized subsets 
#(10 0 0 -10 (1089 / 25) 168.282) of PDF as standards for specific industries and functions. Today, PDF for Archive (PDF/A) and PDF for Exchange 
#(10 0 0 -10 (1089 / 25) 180.637) (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access (PDF/UA) are proposed 
#(10 0 0 -10 (1089 / 25) 192.992) standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM serves as the 
#(10 0 0 -10 (1089 / 25) 205.347) administrator for PDF/A, PDF/E, PDF/UA and PDF/H.
#(6 0 0 -6 36 216.484) l
#(10 0 0 -10 (1089 / 25) 217.702) In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems Incorporated (based upon PDF 
#(10 0 0 -10 (1089 / 25) 230.057) Reference, sixth edition, Adobe Portable Document Format version 1.7, November 2006) and was reviewed, edited 
#(10 0 0 -10 (1089 / 25) 242.412) and adopted, under a special "fast-track procedure", by Technical Committee ISO/TC 171, Document management 
#(10 0 0 -10 (1089 / 25) 254.767) application, Subcommittee SC 2, Application issues, in parallel with its approval by the ISO member bodies.
---
page width: 612
page height: 300
maximum Y: 264 (page height - footer)
output parts: 5
#(10 0 0 -10 36 44.7325) Text with bullets
#(6 0 0 -6 36 55.869) l
#(10 0 0 -10 (1089 / 25) 57.0875) In January 2008, this ISO technical committee approved the final revised documentation for PDF 1.7 as the 
#(10 0 0 -10 (1089 / 25) 69.4425) international standard ISO 32000-1. In July 2008 the ISO document was placed for sale on the ISO web site 
#(10 0 0 -10 (1089 / 25) 81.7975) (http://www.iso.org).'
