outputs
outputImageColorGIF
	 "Generated on 13. Juni 2021 um 18:14:33"

	^'Report
page width: 252
page height: 144
margin: #(0 0 0 0)
layout: 0 252 144 0
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 252
page height: 144
maximum Y: 144 (page height - footer)
output parts: 7
#(10 0 0 -10 0 8.7325) Show GIF image with different scales
0 @ 16.355 line: 252 @ 16.355 0.5
#((280 / 13) 0 0 -20 0 40.355) [image] 
0 @ 44.355 line: 252 @ 44.355 0.5
#((140 / 13) 0 0 -10 77.0 58.355) [image] 
0 @ 62.355 line: 252 @ 62.355 0.5
#((70 / 13) 0 0 -5 154 71.355) [image] '
