outputs
outputHeaderFooterTable
	 "Generated on 13. Juni 2021 um 18:14:30"

	^'Report
page width: 792
page height: 612
margin: #(36 36 36 36)
layout: 36 756 576 36
font: #Helvetica	font size: 10
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 792
page height: 612
maximum Y: 561.174 (page height - footer)
output parts: 4
#(12 0 0 -12 36 571.653) This is the footer; left
#(12 0 0 -12 637.284 571.653) This is the footer; right
#(12 0 0 -12 36 46.479) This is the header; left
#(12 0 0 -12 630.612 46.479) This is the header; right'
