outputs
outputTextFitOnPage
	 "Generated on 13. Juni 2021 um 18:14:35"

	^'Report
page width: 792
page height: 612
margin: #(36 36 36 36)
layout: 36 756 576 36
font: #Helvetica	font size: 12
page number pattern: ''<page>''
page total pattern: ''<total>''
report total pattern: ''<report>''
layout pages: 1
---
page width: 792
page height: 612
maximum Y: 576 (page height - footer)
output parts: 33
''next page'' size: 1
#(12 0 0 -12 36 46.479) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document Format (PDF) 1.7 
#(12 0 0 -12 36 61.305) specification to the American National Standard Institute (ANSI) and the Enterprise Content Management Association (AIIM), for the 
#(12 0 0 -12 36 76.131) purpose of publication by the International Organization for Standardization (ISO).
#(12 0 0 -12 36 90.957) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document Format (PDF) 1.7 
#(12 0 0 -12 36 105.783) specification to the American National Standard Institute (ANSI) and the Enterprise Content Management Association (AIIM), for the 
#(12 0 0 -12 36 120.609) purpose of publication by the International Organization for Standardization (ISO).
#(12 0 0 -12 36 135.435) On January 29, 2007, Adobe Systems Incorporated announced it''s intention to release the full Portable Document Format (PDF) 1.7 
#(12 0 0 -12 36 150.261) specification to the American National Standard Institute (ANSI) and the Enterprise Content Management Association (AIIM), for the 
#(12 0 0 -12 36 165.087) purpose of publication by the International Organization for Standardization (ISO).
#(12 0 0 -12 36 179.913) PDF has become a de facto global standard for more secure and dependable information exchange since Adobe published the 
#(12 0 0 -12 36 194.739) complete PDF specification in 1993. Both government and private industry have come to rely on PDF for the volumes of electronic 
#(12 0 0 -12 36 209.565) records that need to be more securely and reliably shared, managed, and in some cases preserved for generations. Since 1995 
#(12 0 0 -12 36 224.391) Adobe has participated in various working groups that develop technical specifications for publication by ISO and worked within 
#(12 0 0 -12 36 239.217) the ISO process to deliver specialized subsets of PDF as standards for specific industries and functions. Today, PDF for 
#(12 0 0 -12 36 254.043) Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access 
#(12 0 0 -12 36 268.869) (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM 
#(12 0 0 -12 36 283.695) serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.
#(12 0 0 -12 36 298.521) PDF has become a de facto global standard for more secure and dependable information exchange since Adobe published the 
#(12 0 0 -12 36 313.347) complete PDF specification in 1993. Both government and private industry have come to rely on PDF for the volumes of electronic 
#(12 0 0 -12 36 328.173) records that need to be more securely and reliably shared, managed, and in some cases preserved for generations. Since 1995 
#(12 0 0 -12 36 342.999) Adobe has participated in various working groups that develop technical specifications for publication by ISO and worked within 
#(12 0 0 -12 36 357.825) the ISO process to deliver specialized subsets of PDF as standards for specific industries and functions. Today, PDF for 
#(12 0 0 -12 36 372.651) Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access 
#(12 0 0 -12 36 387.477) (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM 
#(12 0 0 -12 36 402.303) serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.
#(12 0 0 -12 36 417.129) PDF has become a de facto global standard for more secure and dependable information exchange since Adobe published the 
#(12 0 0 -12 36 431.955) complete PDF specification in 1993. Both government and private industry have come to rely on PDF for the volumes of electronic 
#(12 0 0 -12 36 446.781) records that need to be more securely and reliably shared, managed, and in some cases preserved for generations. Since 1995 
#(12 0 0 -12 36 461.607) Adobe has participated in various working groups that develop technical specifications for publication by ISO and worked within 
#(12 0 0 -12 36 476.433) the ISO process to deliver specialized subsets of PDF as standards for specific industries and functions. Today, PDF for 
#(12 0 0 -12 36 491.259) Archive (PDF/A) and PDF for Exchange (PDF/X) are ISO standards, and PDF for Engineering (PDF/E) and PDF for Universal Access 
#(12 0 0 -12 36 506.085) (PDF/UA) are proposed standards. Additionally, PDF for Healthcare (PDF/H) is an AIIM proposed Best Practice Guide. AIIM 
#(12 0 0 -12 36 520.911) serves as the administrator for PDF/A, PDF/E, PDF/UA and PDF/H.
---
page width: 792
page height: 612
maximum Y: 576 (page height - footer)
output parts: 8
#(12 0 0 -12 36 46.479) In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth 
#(12 0 0 -12 36 61.305) edition, Adobe Portable Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special 
#(12 0 0 -12 36 76.131) "fast-track procedure", by Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application 
#(12 0 0 -12 36 90.957) issues, in parallel with its approval by the ISO member bodies.
#(12 0 0 -12 36 105.783) In the spring of 2008 the ISO 32000 document was prepared by Adobe Systems Incorporated (based upon PDF Reference, sixth 
#(12 0 0 -12 36 120.609) edition, Adobe Portable Document Format version 1.7, November 2006) and was reviewed, edited and adopted, under a special 
#(12 0 0 -12 36 135.435) "fast-track procedure", by Technical Committee ISO/TC 171, Document management application, Subcommittee SC 2, Application 
#(12 0 0 -12 36 150.261) issues, in parallel with its approval by the ISO member bodies.'
