images
imageStringexample2GifXImage
	^(PDF classAt: #ImageXObject)
		on: ((Valuemap new: 8)
			add: #Subtype -> #Image;
			add: #Type -> #XObject;
			add: #Width -> 239;
			add: #Height -> 114;
			add: #BitsPerComponent -> 8;
			add: #ColorSpace -> ((PDF classAt: #Indexed)
				base: #DeviceRGB
				number: 255
				bytes: (ByteArray fromASCII85String: '!!!"L!!!"L!.]S"!!%P"!.Y''"JAAt9_VDo''b4#B2!!!!-!!!l:!$_ID1B7D9!!#7a!)*@m<r`54!"
	:X`$q1.)9)oB0!"iB7&SqFl5QE?i!&8g#3K=))QN1?$!*c,s?EF3>AcQGO$ig89!"989,n)S&$t-1LBX
	8_-_BT$\,9mdD+W)FK+sT?O,=#Q[6"M96E[>+h+G@c[Mp*RL&M5Rd."/oe"opLm3\E$;1J:q.963%''Z
	ScEl0pL6N!!#%[AiPn!3fr)c!!#7a&O?g*5U-\&<Eqdq>!Zh\9-Xj<1Drn]9hS_t<Y5=35UBT,1K%+K;
	I3:%?<^_9!*]G6>n-j<22kjA5[Ibq?!^c@@#nWP_HsA(AH4`&!+oh(OChg*AS#F\Mo&ka^gaG.B"%_T9
	/C6pBQ''H]C8TTuXkn4Y&U%_NGEJkJYM!m)kC#)cHSI7''1cKkL*IkogKIdOc5okV[22#m:Ku;c$_rlq
	<&W:$XMdT_INk11gk_m[TNmHjHc1@&P%$3LMPWKJ=3]`?`As[[BPg8`^f''f$XooRq:OPBf+7N%hVR@0
	J2VeA2gHUOd0Vla8MXc$nsXg4tKVlnP:Xl%4$g"3@_pT<TTY3FfOAcT8O3j[_`[GLYds4b!^s0uu#]lu
	NNIl4`uCUodP^9F3@g=j6sn%sK5`e6(_NFp2M`l?lK_VXq%mek,urlg9dah+OtcHatje^!.Fc1_.kO?1
	jU:=f+:gA_-*SQ4U?>M5ruh7eBngRR*UVV^1Dh;-oBgu[^q>32htlG82<aHGN&XQ\KrkND$jrq,CPrpR
	j[m_t.RcBRbWh<jLJmdBN-rTO+%Mt>],o@^MBh7NFEkP"WCp]''^Vs7c<fs8TN>r6UT*fol<eSc%3?s6
	$N^kI^ZYao:b_s7NSqouR10ci<aks8TP-r7(cHh>dK<s8Mfmrr2rsm@^,JJ:N1M!!!$!!<<''!!!*''!
	!<3''!s8W-!~>'));
			add: #Length -> 1362;
			add: #Filter -> #FlateDecode;
			yourself)
		externalBytes: (ByteArray fromASCII85String: 'GhVQ;H#OEs*!c!-V_`%&TiqU''Y@poUl@k,G3f6NmWj_Rc%9bV]NJnYuSlA.`''k^.H?kmdr`d$OZW,
	X%6Q)]MRA''H^="e!S&WriVoRb,<&Hgf_%c0hH%dO)`tPg''tMIb@NRHbU"%":1eo_D?hNKQeF&8bdoP
	+fO@>a>2D3.aEYaKtZYQ^";\^DItV6o6M+[a!)1RS&gO7QX''^''j-RsQUt/f2S"a`j7.G<^7A+T5`QP
	*4a]tN-\08oJQl].$4f''e''cU5=((T!,KFKBddnW[;oWCEli<J?\_mR*o^j*03n\W"D1(rZsKgmI];0
	/V4!Hn1Dmq2sk%a$n%Ug2N;qI4+5CqsPLI5K!.R=0=_s6'']W_\2[%=P)JjZ2YXi[hk\:Eaa[N3B320s
	l=e)QQb4sl_\.0,H.W4:6KqF:>VTQ)5?a_OrSWVbs&l%cM2SpJNR8JEjCm<*Q7I7&mg7j''`GENlrhd0
	\Epj9l>j3Y:,W![&$BeGoi<lY:(JM.sPJe^6VE)DMBm*))m?[X7WTOZ#es77Qr[l.L`c,3hSMsf];7YV
	^?L/I%Y&kBPlu9YnY;1$9/NiK\)[oTGaNPC4hJh"7jap-JB%!iKLTS)!''5gXrL+$sE2hoY$I3V&a9cG
	d-ogZ?7&K,Q[BA%2k;@W1^$HYei^JqoBk/<76K(9p1(tFekNL;j!fClOdqWoFcWgfd;oA\i78)70br-9
	k%2lK-cau*aq@BfaTCg:\iQD%EF*Cj,bE#FA)d2mj;Zok6Vk_\$Se(hIa)$?3[)jXa#bLCRF/XMsb>g=
	?K3`3HRAT#\;6].;4m-YMF11S(C%=KfVW2J=Y>kU.WioZ/#7U_=`qVmc]*pQ(o^ZP6cMMn[gR9XZoD&0
	d`i]J1`!]arkCVlmM[%dK5i`1(p8Yf=r/L?NWk$#-um5#;''^YO:+A*=9aaB7c=$cOEqNN-%:8<1$>L,
	&_`''kgLJa`*\YkR-Q?os[mR3\I"2mU3B9B)Wt"1mVFOO<0\DWa2=W1rmrXeDE_Z5\DJ9b9\Zu9PZ[e\
	I@Yl9:#7P6?;gJE]#>]C/*->]CVlPiW/Si,YM%jOed^iJ1OZ!p#a:(AJ]3Z.dVDsmlU-_EP^K031>.\''
	<6N2MS!^XWX1MVl6XH0H*>!F[bkFp44mMUi>R-[aLYRpb"kB''Rnm3Q=7F`uqb\NI8.=I;7Of1:=5S#t
	oF5X)hY-4\jK87B\nN+BhK^LKg@%+A-o/>k)F3HZnGD3l^+i[@f6QH*,i5q2iV)H06^tVDJO#ljE;.%r
	jA`h3jpkaGW]1lkT24`-PWSC*PkWnZPW(Y$%o<@+]p$&^ZU4LmKtF`(>]hbCkWJ4cJ=-.>ZFPJ0<].n2
	7P=]:F(U_DH23sU2''CF"]kr]8>3VT]Io/2nBVb2BnR?rr2K#de*tstb=fY&@AZYY#Aa"s#o2+OioDfY
	NDnC!DO/tGCSc[bmG:b/DMDPsO''Xs3##/8eVE%.YZkE5k*8h\XpF!j"[kX-U.o`7sk\jC_/TgJTGd].
	2QJUFkLa2PSYPElsQ;q:<f)NaF[#M5-lOEWFI"iI<_,GNq,]"d65]NsC&g&UY4UcaR8nAj",h\cqqpFc
	C$aqN+TR-2FnoDpR`JI>`@!Z/A^"YObF$XDTk(V%6a/oZ@L>i5Z"\A/8#E.JC%huX_)^]c?0JI>`@!Z/
	A^"YObF$XDTk(V%6a/oZ@L>i5Z"\A0*iq&fNlKR!~>')
