images
imageStringexample1GifXImage
	^(PDF classAt: #ImageXObject)
		on: ((Valuemap new: 8)
			add: #Subtype -> #Image;
			add: #Type -> #XObject;
			add: #Width -> 227;
			add: #Height -> 101;
			add: #BitsPerComponent -> 8;
			add: #ColorSpace -> ((PDF classAt: #Indexed)
				base: #DeviceRGB
				number: 255
				bytes: (ByteArray fromASCII85String: '!!!"L!!!"L!.]S"!!%P"!.Y''"JAAt9^tc`&b4#B2!!!!:!!"5D!&FTT3WK.L!!$"!!+l3K3WL$o!#]
	)C)0l3,MZ>JY!''62A5^!,mJ,i''*!(NLZ?=En=T`AE$!+ogCB!rQW!#Yb])#uH1!)"10<>cYl)&[];?
	Af\-PSmf#)0W>(G.f+#5UINd,8kbO,9nFkbUFti/hSb6A?e%SdQ.A?3^>_cA[FL[gHkl?7K=;m!$ar51
	I`7-5WU,T5VkZKX[%fd7\/.*9heM`;I0>''?2u3S!+]CR)-SnV?<Sm`>$>77iai*MAcQFT3fmoaARqq,
	A$,33[f:#SBQb72Fr<PdF)uM_Ed#.^I51eL0en)52g]muKu;c#`oi7)!/i''HMa//<5U24g%ujmHO(''
	MqXiu^7XcCWfMp1[LcM*D]!0B6&O?.!9=q[!416gAYOP@4*g]*g6)4=tRSS''+6R@0W!pRuOMTQWf$HT
	@mJ6)''NjVl-GcbiZ$6,HH5YXc$MfbiZ%in#baKY3FfOAcT8O3jGZV[f>*js8TcU1VIrm]mhoPWb9#IQ
	bK\q\[8HJ\qdoOg:cYE^%(@#nbgC[0u]\^`M\:*Z^o+U`ls?+b_o-9NaC#$;TteWah+Oo_n44>cHa_pc
	fWp&k5!6us4<fNe@hL)cc=V^cIURlf%/F(oDRF*3n^''(i1F60^44nlSDE"uhVQ!''hVR&Cjkfb3g]-$
	^rr2)W>32l!kJi2;acu#Fh<3t@kND$jrVl$"AEh-Jn''cXOf8/hQg[O=_mdBN4rVc9"H1B@''pXX]_fs
	pe>kOJ)Up@e4OrT<YIn,*.Zqu?Zq[V#E\MuVOnr7RY@k,nUEa8P/Erpn22ornDc^&RuRs8TP-s3CZCfD
	km-rr2-\s7$$fqYpKnzzzzzzz!!*#pn=ZGMIt)tJ!!!$!!<<''!!!*''!!<3''!s8W-!~>'));
			add: #Length -> 1177;
			add: #Filter -> #FlateDecode;
			yourself)
		externalBytes: (ByteArray fromASCII85String: 'GhVQ;I;IDD*!c!4c\m<%L`iA]U,$0<''IVfX@jmd?8p1IkKE-T2).4<>1fG!N\!tHs8pF27''MqA]%0
	e+06rOZ(Rk^KgfRPE(]A<''CiD6&3p3OD9]sbBPf%]Y_d?a42hsPR#p3A8j<J^[MfEJ+.i]8J<;6h$=9
	UJ](2CL(Ug]qg+B8:0pR<g*(kuQ0in!StRfqbAV,M(K[q)*\Is,!6Pd@Qa''5tkpJj;-.uClK::&o[Z7
	BH"mH.Yek^&Yc_Jn;,!CjPUsQU$9g-l<]VN7M=aB5,KEDS*a1/eqfV"4[[p=eHeJj6L.5aM4DGgCa''&
	mU7<,\`+\t>&h`^mXG(It2PA!>W7@gaD#E(U;NH<r$W*]gUJ[a\<)SNC''Ld4O]YPs:/,5=r:H&,Pin-
	[t,?eE2R`B6?gCP[&=q\sZ0g^;NLm<eF0&ib-qU'';,7.tPeG!mt4RSqF:?Gr#:SK3R:M#SPo1;$HNLi
	mX;oh''Tn7#5qX/)j<ELaj.>%RcTVcIJ.3k3(og4IeG%kjuQsX,At''/(gAU10:N2d#f0pIOF`C1("0@
	>Br2,U-@7T+@[/KOF*+-aZ\9]^ucX&E`Ah_mYG=K1c6`T6:HH0?gPq"GjMt*]Fmpp.\:7=K^=MP$Y!3H
	LWNeYGDTFX1-30L8ff+TqOqWN&-S\F]g60R2GM`BSg_JYqL"d8MH0iJE$;[/i"u(*0g1Xt3#orVTZC.A
	0prkRc+0BFqj`J.miZ^;h4"ZBZ#Tq1I7s95`V&u&1dk3!R[3_MlRu8+&Pl_p_u/:?U8/)1aU!ZHG/oAB
	1*bMN*CSR!>G<<EKp#mkr]YgajE%''V5Wi,U3UBi,DFQ22SJ2S(it_Ii9@WB1#NDXc-/T?GYnBbIZ@m#
	WLZsUmqREQbjWPkHYU%mbAG#HTllY%qV2C$u`EZmLPO?oF:)3Mc+HY@hb5DH`5@Ph/#nqA9SW$[8S*>U
	E*1Tkf+YgQCF;$idI1G)\`)$.*lH8G3Y0)m3oROU4as<_f&:o)XLt>Zl/j/]MJf*6(<p9M])=jesbOZW
	Kj3UDEE:jl1G\R[/p>B/lUYfJ=h[>)BArQHdZ$"nZ8(rD5Z:H4KrRcI*r7B%(aCF12FoV;?Fk:*Po$Yb
	5Gu#N>m30BY9_e>^*o$PZCIbN[kh:TE!mBdSdO!To7f7a>+heM''+50IrL4=Dqm]1UBNPi4E_g5;1Nme
	Z$:\^T@(MfF]i#,"sr9PV>,;6skQC#(?qS##Z_@I1W`7dh$6VRE@T(''_4GYr7DIP4T.S@"/[W?ZTIrU
	\;>dgFj..([Q^`2:O%B-n9d(M^Ukf.2Q[Y@#(.9tm3Y$amr$dnRUGnGH2*R;O]eClca6Bq^#>18Z"M8>
	[gsh>#p_%9X/0.`#7E8DCAOAK5S=8h:l!OdtXVM["P<#9j_1#Xfd:&Vr[T+qT;26m)OCLd2(e&:k*T+9
	E.25Qi8BJI"Xd!YL5R"<nD.#Xfd:&Vr[T+qRJZ"7)S3O8~>')
