images
imageStringexample3GifXImage
	^(PDF classAt: #ImageXObject)
		on: ((Valuemap new: 8)
			add: #Subtype -> #Image;
			add: #Type -> #XObject;
			add: #Width -> 229;
			add: #Height -> 107;
			add: #BitsPerComponent -> 8;
			add: #ColorSpace -> ((PDF classAt: #Indexed)
				base: #DeviceRGB
				number: 255
				bytes: (ByteArray fromASCII85String: '!!!"L!!!"L!.]S"!!%P"!.Y''"JAAt9_VDo''b4#B2!!*''.!!!l:!$_IF0`V27!!#=c!)*@mAH3-1!
	!H4#''57F]>Q>Xe!$a`/,DuOQL&`rT!''6,?3g''J.EWA@T!(NLZ@q5RDT`AE$$ihR^1J7d\Zl&ig)ZW
	YO>$`(QL`''N`+((`[G.eoE_BT$\,9mdD+W_jn;^4P9,>3&%M974H&M>[g1&q;1$ii-s3\sEM2.WsLBV
	[AIeiEeC3+]HVOO-Cbf0BK>5QDNd!%^G]$p@Qo6"l3BG,ITN\j21q9/@G[9heY#!*)91>"^YL;GpJ#=^
	D(.?2u3Z!+fFG!+$N_A3#]W<Bshr=''f3H>[WV"NPSqldpB09AH4`%AS#>QjCYk#CJ-I"?=%;YBQB]bE
	N7W6)$"gt)0RkLG!Hpg?7^825]_!fG+#OU]]t###(&''ZI5Em35okeI)MD0LLL)NbDafAthL`W-M^&4[
	3>%07,E,Y6Md@rm?oj3R>)\KQMlk3_`oiH<s,f#EO?*B+3t[Q83flC7O]iB\Bel#u=,kMrOP@477N%b''
	/=U2lT8T,*R@0VZfq$g[S_<_7BKW,43MUgdVl-Gi`20SB,HZl<YH>+4bc%YhkH<XbXQ0,Zl/&j\!3rMq
	Ze=iVs4b!^s0l`"]m)?HGX/d''DS<0=\[8HMg=j6sn%J8h_L4G]MeKqhAAXm8`M\:*Z(/eO`5^ZI_VXq
	"lMA__5g5-Yac9]OTQ\GhWQrf7eahG;jnR$nrmd?3e@hL)ac"]qa4o@]f%/F*r;PH43np3,fr0)M^44h
	LW8$''sh;+sbhVR@qB''R3dkK&kJb,X[]h<!_8kND$jrVZ*&N:,`^mdBN5]m9IuN:Yc.oA$qSn\+Vgp%
	SC\s0cP;f:2fpOT".<r9(]ikf<_d`r>G\s8KG+oZ7(,d/X$ps8LsUrr2orn"?>LG)LD@!!!$!!<<''!!
	!*''!!<3''!s8W-!~>'));
			add: #Length -> 1730;
			add: #Filter -> #FlateDecode;
			yourself)
		externalBytes: (ByteArray fromASCII85String: 'GhVPQHW1\Z*67N?S[1S;i1nN#_TXjc1@93^&BM3Ybt$o3T[:nT4_dcN*h$b2BFd.gQ-p&f8pfeoW(+.
	9=#:kZgsm-Z-WH,Am`aqAIWljF1V7l)`O`@urLRTom`]U!HU%9(mdE=NKH;6t''ijVAC*8!LD@Kd3),f
	%Ab0IMjKjmCU&b-LH"G5Z)5oR.HBTSq[=E/lKdm:]`T^E?Tn<G.Bfa!5t*fu''!BFN!uoTUmjhB7)\Ik
	-`n52IE)Ahp/FXs''(``W21N$G<<+?1n31I#YQaDYo0(e3_T)J\4N;>\d2/[;lul+]K]mT,.Za,WOpG*
	FuD[Op`OUoiu8;bpPh!?X>(o0,l`4!2SW7csY2#IAR0SB?(<e6974l`Mel!LE9?$5X@[C69?(UaLIFSJ
	T%/&YU?[df@hG-loe]If4kV4n+u;T5WU/WLVjo@X)!eSKkfkUi#q-r\!7R9f0_u[d9[s=4fe`P8sJhui
	=-ZP\/IXSSb?3bOOL3aUi_ka6>mJZm1Q0W!2Q/bF1YLLNZ9ie%*''@o+0o>Q5@*PGd+1''pp@6;[Fq8(
	JaC=6K7tTe)$$,''WE$5`E?d491kutP#O%JSna5YclEq]$oS-l@Ki#nFs?"3>Y`0;6C\LUq+,Bo[e''i
	LB(+m#l12M/:?!GQ/iAt2r]bq1#.T]EUA=KMm>=,XX="<fV;idm=GC''mtqK?M''gb&@6(;1-.u30LIq
	S>f8LrZMT.c";JWB&pLTd6a;8"^h;/o!^lG53ij''i98CuW\%k9gEIGsQ_;r.INTLsG/''-3[biUQKB+
	#BRB1''fZ3m@lonX%Pj.!ZtK/?UF+:6Mc+f(CrARqo2aHsVK@iUX@$sED63Q<3M!^gk\*OCj>Pu5.t,;
	S==Cs53Y7>0/Z1jDlUrZGAD$Hc!i8!4"q/8K>Qag.U>chO_'',$mSq>UDd,6N1.N11#PK91@B`e._hNN
	d&e=06OnDI#.3O>P0hoK"+fVKJZ4qbp*clSEF/d;gJs`D--Z>Q5:hE,"hZQ.U5JZXj0)Pj=)t6''Z60l
	"+OGOjP#9i[7(2gE''DF3IG$-7''64n8))cg+e_&uLf6^=XM-KX)HdNrZQ:BmG8hLdO%p=6.+>7QW6&G
	>R2MQ$nlZOuWdX/bqd,C)k526>RMC<&Zp7-fJ/NOE?T15\^T=oo>D(AJu.=%ldo1"fhZ;AQBaf9nIi#Y
	0%F,n#Aj)A>ASQ-^5nbZHLM)V2Yq:?AH4d\_#X,/3mO9c4:`O_k!4LFeA=7%5"G-"<TGfLjBYYRnPIB[
	S''Bf''1d>+ma&^?iPKG+i7.TsM,PC-aho6@mpAZ*LGaA-TrqRLG:KY9R1!<Fj2%XIFH>\*nWW#I(NsD
	9FDn[\Yh:U,-b*8uWAX*r#rYF^t%deSoYs-KRiqB($m12NK.M6C"J(2DQG"_K``p5ZS2%&$"r]:O\<^U
	f`tB_c:N!eRfAqbAa[O1gZjb=6L]ip<dt%n2^XaAB-0:\@R.!@ntP:an%#*nN^9.IQ5.tH)=H__b_Xr0
	aeE&&eDor.2m$WL+o"85Y=/Ld^QS)reAA_cj4/#L$>&HU0_D.?h(LOS:aME/D1%U098l`igQSs6Yt>#K
	S6a4%7IZ+SjLqFBg%u8)1LO9C"<ld+..dcU(XVK.1/Wi.3sVCO;''HJOKMlI@2#rBhXL$o_0N1X([7;2
	>*,9o#/8+c/L=KeM-iff+\c-0T::r\^Q?b3iOo%j>9uU''n\XnL/C`i?i+a],ao>oSjM3->ncIR67?bO
	^e;t$2W<=M@XH++;f''K7$7ia*uXEXUuUeIlUZ^O*:@hR\hi^?FD8KpDHc%R+)@SPaNJln4SC!N<nGAb
	bJ&9MR+jrpt^l$NNjI0&a[f]Wi1ZR?LUL&:;&DOe9Z+O_o]U]3O5,k)Lh_ELlH5-`M!GhCR?LTUZ.5;5
	&bjnmI8Bh[LgVoFrNB6h&laIVFa]i-II9"h*UKO0ic)cM/.0fem#DBQtrG''0)iKkkJ4*3N`k+J3rG#"
	ZY[fSlYPd^9P1P>*@F$[LXJZZ;FrGi7hk)27i"!2TaAo7[!W?s+''t.j"6,&p;1R1PNURGmYGc%$FArK
	[q]EF+gF0Z=SEd?.CYLcO4j"Y+(Kl#XFuN.NPV=XVQVdO;*jE;Fh-d+Xn[jUlZ:R6;g>]8KfN.KqseEP
	!W&;$:uBi,_`%U''Ttd4qB%?kWIt~>')
