images
imageStringexample5GifXImage
	^(PDF classAt: #ImageXObject)
		on: ((Valuemap new: 8)
			add: #Subtype -> #Image;
			add: #Type -> #XObject;
			add: #Width -> 304;
			add: #Height -> 103;
			add: #BitsPerComponent -> 8;
			add: #ColorSpace -> ((PDF classAt: #Indexed)
				base: #DeviceRGB
				number: 255
				bytes: (ByteArray fromASCII85String: 'rrE''!!!!$"$ig8F!!"5D!A=EQ63%0^!!$(#!+u9A=9&qL!#]AK)0l3,5QE?i!'',B+4cBA-GQ:7("(
	&)0FMA5?9+bjD)$!YS)0m)hSJbap).&sZ@B(5j^**IV,9mdD+Whpo<[17X,DjPc!#7+=/i!V22%_l*93
	X2FF#@X,3rf7A!#\*''!''gMr7K=;k!%^G:1IV:]7f[Wr,7Hb"5"7e\69p/k6&@j0><uq]95p^mH+H4u
	a$uTP5n!`d,7I4$),*^t84]7AFMCg@,u[Gm;GpCj?!:''BP>7"K:l<ClS]ap-c;:=m?2st1''`_SY).#
	uo?=$Q8>[(H@O''[aW?EN3m%KKrU1L_S<AnGXf@\@+k^gsM)CgLFgE<''ZcBPOEsDlh<$Xkn."!-A33E
	<''Zo!-EB%!-T4tFr<)Z2%b!s)0AE>G%EpXDNf-_F)$`5F.L*gZ.=''1l?''f@J3b3&H[C7YkCbApKff
	?n?7^h?4GS]IOYI9&?s8J/B8hk^N5=;,`93*!mu5K]PWfbEDNgN4:6C[$QpG;R8-#/NFIc''QVeA2eL6
	J6fR@0J2R]D47YfrZOfq6LFS(dY-hnQ%cVQ.b9V9mu!d-7Z=,H5;UX^YbAMdENDBWnYEXOuC3hoMq[qQ
	YpA\XeqlS<U7YMmTjuZerd2h=J-p0>DT/^3DNKF[s6.A%J"H]rR(&dH\HtmCrGr^]33.MeL/5U;k3m_V
	DoGh;-''''m`^SVb`7+pTQ\PTPK^D2cd0q_hseqJpWM^pcKG5Qo_m:*9\5hFe]aK5f%/I6o%KU3fr92K
	\rPRZY276_h9Wjkgt^cCf%f3MjlPU\kNCU_o\SiAg\_!3XCgY%E9Y?''jib''jeAU;''i8sh6n%Z3q_M
	7U4TC1[jmHVaYm-O6?rqX9Nprn`ohQ-8$\+A@enaX<dp@eIan,ChIrS*k?kI^ZTc2R.Krpd]%ouR10ci
	3^js7tmYs1eU5i;W`T~>'));
			add: #Length -> 2360;
			add: #Filter -> #FlateDecode;
			yourself)
		externalBytes: (ByteArray fromASCII85String: 'GhVQ>$Zo<[*<>U#[0=PkGb>]lHW6(1TCjppF%/4,@E@r^DVj>/MS"+\D!Ig[](fBUY[]!)=&`YK:mY?
	Ged(#IURP(=bLn<]5Tkh%$nrV<p5rcNLY^DPoDa75p"e]cRsWW2(Adu*F7W3)oh4^+htOm8#]t01F<l.
	a%cHVknZX%`$hLSAP#i_9S&)eJf49/0m9BHDQD[J_&72)F''Rfq/btBTT@"X<6TpOHEmEEbq3YI?6+6s
	XsM+RH)H8-qR,&J<iQBF<%)Cc0Xq3[#&acQ$4Tul_(\^q#GATZ$JojUo?U_r)tVI''+1.!lDC02jO[0Z
	gAVHeJ"R>E>cQlD:19dkB5]ZY.gh`;6)V8aT+BS%WcE9$5@Ek=AUJ:QEOe>_gZ+`\/D^l=DYhDm.GZe@
	^)T''(>QdZ(peY>C@HOjF,4i.oh#L1./6NmsImAT7>Iu_q&/b*-HbX^1,t=LTbYYT"(-EbR=<E^_?HWn
	SJ,i4YMb(`a5.hO%Mu%G5^B/l\iuLWZJt7:]6+ka/E)1hQ`6W[#He.Z%e"OAA4BC2SDR7^=Ds7`p(>^D
	=cCc?`%-[:8ms]]VO<.jG`HG\cIH[jd!]s(BoH36cfZ&8%QW^W(Ut4P>JHbODAZq=+Z0lQS]o6o''(WN
	Pk=gi#rUYJPVh:`1Ln@]*pJWf`f01G_ptYJ+$4Hd&aElP;PEFb-.p"kk[/uq_?nrt??"\B$f..6e.Ub0
	\A1`TlHj=ahP3iZFR''=ok$b7QkO1p#X/M@5KCp..-*YS[G.S`5a^3^a^9b?"j#b1))inh/I0\WdUSW8
	''\j8-Xl''6S`0WAFO8Es6c>q5[SSP#N@D+RF6kac)QZY,cr7DKm_a^1V/rAp?;XS"`M-H)t(__*Tt?;
	U$[HKhSnE7)=Bbf#DGF0E)<*[b#Y\5T0<$c!a%a^1HE#Eldq2`2abVpfEi6U%4<P+Ge-:EY<3)V;Wt&M
	$U)065Zl)"?''#l>-+f.4N_AcoL"o-BaC^G<flZXM##hNlSt/oLk0sTCn*)#ECkQn:K\4TC5U(X2fEP9
	o)k50acOY*Qh1lYC\Bs%bUL2K^sID$c`-b.kdCj]e_=P\RN<hi"[oa/$YD+H.\$I,1S=ZcRM:D4$2hVp
	%Fk<j(*FX.pUn6Pg+"9<fhU<?V=A%ZhmDd162`d)>$9b]i_EmG`C^iI#k*t:/8]\nMGNV.b=jheQlK7#
	I/XMmL.)dq5!*5I?KHJbjmO!^0>j(''omXoo.l9HpQ>l7PukG;oP#V]4J/Mh9\eH@p3Bj9jFuI6r:<i7
	?KLspf$J1NK[.abm*Ae*Ih0mh9nW,u_7dA1FR\9u2lIN''gHiONp*,)hc1p4''c=5+k4V#-;1Hr>#q=^
	91f156d7:(U(#ZZ:$5:nV^1M"*E3o@8JlKE(7]\pc(\IX/iN_A#]1*7<5b9t9),t?`"#F.g>gX2;NK$h
	+netYi5bJ.P!dgao0ere^OGTFF;/\L*shcO%Wq@.^k*S4''Vpr''fPArn*ora,UOd<P(;:FF.p[Tm8+K
	nnPh7rRS.bNm_gQ!gg<#A]We4YlohGga95B,5`''DHkLafA80t;rZnVP9UtS[J9uAYMA1,5umB"`8''\
	&QDH:nGPT2aFqpuK0S_[hp)9CSo(_du2tlHIa?4u&?Mf8P=*CLIY0OINX]J^`d&$mqo_RJDB\o3.B[2s
	h]M@:9(()S>S-R^N!?6@@It#mmE-:7]>."C+J,\BsWn3nhn#KX<c7jKA`T#X;H>h_!Eqd!?bel5@d&_@
	=2ApqCp@9;(Y?RTuS\;"PjDKXN;n6L^74e=sH?</"=hWNW"#!%D]WthL2Sb6qHu=CoZ.FoYQP-9]p!Ng
	Dm*7-1HRkCm].OEU#/CS8rP`kr%m.[%FMJ:Yb?fN''pA$r_on)c_%%300ETZjopL#irDgutWr380o0@)
	H-K5Xs)hl-h#bX[#cIshl@pUr''=`,#DPrL+NS>qXC&.1ccq%D3G`K!5m#?MZ^G@W&6OfC594Q1iEA[^
	P7c0DfTB]''NMCeLB=)na2ZrZ1/5-jJe30H,2gpHR$a%*^HSLG]6fEfoOgW?o@N.7Z@(!@^=DnRakNG(
	L:5$2@V2U%D".bA$1+.)M,gI0k7E''V$`"Gic(Q*c#npoDg]_8rIFG*F''Gp>%*I(4U:UeZ"gV<&!]VG
	!e4Em:^IghDR/1q*Wa3%@p>bmWGi7+$a7[X($R0''A"c#hA2J*JJ.rDR6^ERU*QhBRg&RG8&SRb7V"rM
	X!W8!B.O1jskH2UgI=ai$&(G07;91b)TE9>&tVr5D,/&PrmC3*VP?S@Le&(MM?dn.<Y\mhr&LU1Jg.-L
	3QXAgeXg,Ym/A9T5,U^a!ir^Q`gqAGs_f:\#?lc997MWX!/0nZl3E?(kQOlWb(e3j?V\5(k@V"r)T/bi
	qFE%]cM0;de-HKk;''F,qr/;n3Dsa`4;CO`eI8EkCg3?4X7VMT2;gRFD85T29upS`+kX-Ph2_[NIR(K8
	OFOp<]em"[DC0c3CpPn!_De]-aX+RJNtUaZU!UrQ%-thVUS&RnQ!CKQ]0Xkq5Ef_/&oG)>N!*lCi%Of0
	]&k^BW<B<*jV<hr!sf1d:ZW)QCUSWHMJ+U"+,9:L"<7c@]*ndUHg7SLD&!T7L=$[HR24EdC/Gk9\q:7P
	D7QFQ0TP0l_4$a3s##Z")R)@U;o;E%``F-sp?,]V<dXos7m>r@:q:AaL40_p(DA/)k,D]""*kqD''U-g
	rlYr>34>S.dg:JcMfs?pS.]fOaD($m_ulL(\coqgl$N!0CHfm\/4o!?JLHcEA-b!]snmQROTsF&.CHSL
	tp1FQP^&5+T`k^ZK!6#JdlUa>AS''4?8fHH/)^+.?>hO5]o%/nO\ijT''a28_C_F6Z0e^]"''G<qO$ZN
	:Y?8>RnUd@e)mT%1uiedkE!cU$,\X0^j`[)0K0<b,9?=G1sE''_n7?<1BA''Y&aW&E*sS\,m91A`_GRM
	)<=Z&^&YB^%CiE1`tMK~>')
