images
imageStringexample4GifXImage
	^(PDF classAt: #ImageXObject)
		on: ((Valuemap new: 8)
			add: #Subtype -> #Image;
			add: #Type -> #XObject;
			add: #Width -> 217;
			add: #Height -> 89;
			add: #BitsPerComponent -> 8;
			add: #ColorSpace -> ((PDF classAt: #Indexed)
				base: #DeviceRGB
				number: 255
				bytes: (ByteArray fromASCII85String: '!!!"L!!!"L!.]S"!!%P"!.Y''"JAAt9_VDo''b4#B2!!!!:!!"5D!%7gM1B7D9!!#7a!)*@m<r`54!"
	;Bu$r$^6=TB">!"j#I,<u5RMZ>;R!%`j*3f3nuO9\FH!**>*@q5RDT`AE$$ig89!$Vh-9+3Ui!bAYJ!"
	KTOYT8//,6.]g,7u(B(aC7K,=#0P5[G[$AKsig-"*>hM9@RQ!A5uW."/oh&NV^@>;Jon1KAl]@#HsTZS
	cEl3fr)T"op[aAiPgr643cY!"hI@$p[fs6"l3S,7$pu),3h"7pK:l?B7[$Jkh3?:S$$9&-,]d)-&pJ>"
	^YM<Ba;Y;H-t+=/b"_!!$I.AQpr.A3#]W<^L(u>[LiF?!r_"CoCa/aCP?3A.ATIL6,c%_-X8''B"%_Z1
	_FXk)08G$CgLF]BP;79SSt(=C8TR*YM"(:!-]h"G%Ep[F)uPfWH>c9F1q$j1&uYU0mtl;J3b3//.@252
	2#m:Ku;c!_WQTlmu&CjN&_K.?oj6W>F0M7N/kK/`oi?+o8ta9O?*B''3]`?`Asbk"OOEHWg&-rd[[ge\
	T8T,*R@0sd4K#*TWl_07bikhUorVOGW,,eBMeTAsZEMdEXl%4$g"3@gqlS`LY3FfOAcT8O3jWKNZcM(2
	ho<,)gU@.^\8O%6Gr<6`8[t%(]@tuQhXA&=q8.P?`e6(eKgrq;BYfgAae4+&`l?$T]u]+&`9mEDpAW9o
	5g50XcHa_]k1S&SpXPU,f%/F&q#/s/3o$</gSo>NgnW`_^>@`''g]-$^rr;)]B&gXXkfAtHa/n=OQg!8
	]kNBkJkNCpm]]f:lm_t.PcBdqMPj[SfmHVa[mdBnpMtl#+oA$kMhS]*NkOnQBo`"(S[V#HaOo<psqrYE
	fm(WGfa8bVJs7NSqpV$S"bl7IirqG@Ns0ht*d/X+%rr2]lrr2rsm%C#IJ:N1M!!!$!!<<''!!!*''!!<
	3''!s8W-!~>'));
			add: #Length -> 1650;
			add: #Filter -> #FlateDecode;
			yourself)
		externalBytes: (ByteArray fromASCII85String: 'GhVPRCN*3@''Z]sC1G(%POI&e+;?:c@''j@5CV&$1h@^%9/>SNu&W8a"L^dj0;(4fY]fW(n1]2f&)KV
	=)ZUpL[^4sm^sL?\m\@%=ZmCd*46hUcYN2m4QrE9I3J^"FYY-i:N&p?\BA]%s59/@emA0QKT6S.N5c/@
	V;CiG)ZWKQr>[R,`E>@!_Q#2R$:QVE2T_0jnqa-p>C/U!a,)q_5ia$cYbQqHu/Z1Qjji!+Q77#4iZ4N%
	pO3gkGop<sB_5''*R37b$qsS:K@Sro88O6j"dH>Gu8ug`s_FrgPW;+jXWNH:_h!B<^d/O3-I>#Y\FWka
	V2E^^9*TcF2<lRGYNKj5C%MW0\OL/C"hVFdc9idcGB%&BnN._jfT^[/-nSP&Ne;D4#,n/WR:\5nq\M;q
	XA@(_VSM3,1gE.p=&`t"Ftb''Q,aOF#)WMaV,D"JN=JYYHX1NGTm3Aj1OI:kWRE[J(a4O`*`l%/W!@Kf
	aX=?F/SQ!:aH_"'';<*2;$(!^TR%*>c[Ihlf1h-:Vq6>Qpbl)BL,6n"G6-:<9q:;Zf70KZW5BHD2S@GL
	GB!>balC9S\q6i/:F,XAC\`KA,AWY8mUtk''h%Lcg.)7e[%`3FroW?Z^C-7_E_gto+;k)''5a+ZLGCJA
	IGL&25IYD[UI%Jk>\BTh39^0Zg&c;R&Bn*XjBCX#fEgOaY"Y30LFpH&JtqKa6WtFuTK''=qF4c''PK0*
	:OKC.r;eW4](AM3f%CLN#FmMoM0_r2%SU#k''++rme_u>A9*2oqb,T:0PQ3Cc%0;Eo"R1NKm%I[-QQa-
	I,.lgLp.JfTq^EBb9V-rm"61jFN8t\hXTWE!0RJ%5jX$5Q2i_C[?17P?EgQD/0Ok,V`.9?R/7+%BZ\e2
	b^$MUi)*uoR.Pe$\6$F5G"pQS:V@3s3P?CZ*6n#As\/D2H&,q2KobTn,)#O``hXLSNB@@srY-D-k?`0?
	4MY5or<*oBhd$3s/JTWTfc!,A=k-Bs3f<QLq]@=PkbrE[g:gT^lR_>0s"bSe&/V_=8/NDj"&<nUF)r,Q
	@b.N/#51j3q(TRbi"G2.:B+F]5%3Wkkp.)_e1N%)C4S1h0Mlq=K`F.jeU2c*nBN0s4=AK7GZ^%632=q#
	TSX[+ZcSp&l=u1&0e-lD*D5EY%U2c*g<X*gt=Hn_A",92E=Q#9PXTs0`C/R,8XM7e(o)H@A@N/%ME*E!
	EFKO`aa@=/L`ba/bh#dma%qFlY5-n)j4.MQ%W.O-aCpl)!qsRN1.JmU=R()htnL<t`#jPqB&(H[=Z5/G
	uYVtZ(A)M,@fnd0[r#IOp=)u-A:`QFCbdWF4f#e6`.oc@>B,^!rikkVPq7"U[%=Cn2#&uc(Y5eLZ5UsP
	NLPA"oU$2O<Q#8e<\`YTJ,E[-U*K&KRK#[.Z+U0`4^]S(6EU\bL<i0CJ4"DWgR+`*B4Z8cE("`ZQ#2Lg
	2K/,I!:pGggS8LV:N+P><a#roEb(K]s,``;"eHI-o?Qg>m,pbX6F75G>FOd_0i=8Me%IPdtjJI8@N^K+
	TplmVKQuk!2MtQR;0"UmnZ9mK#\#7Pe:Kf.b:F;G8AqHFYaTdrdhYp6kXaCck(>*ga)ReR$D4A<A,=V(
	:He&Q2D"*qLb^!67k8V-59[]dq3FMj3RBp)%s5YZ)JIU+iBuJ/SQ.dri9ss0gYQ_()`_ANL9K-t?/(Sb
	$gR,i>D8=GuQq%)"AhVX`<.W7Oje>i3oSI!<\d##N]"AXL5)9OeC1dnBZiMCOM^5>%AX[A1!FRpiEe3R
	_R+%)m`SkD:n$E,]/"A20^Sh"0e\Bu!-7O6a''^ljqD1T:<pNb=NJ(O>''32l=A)mHYE_O^/#<>8[*5,
	m)IIDJW(H)P+IVp+r7W<moj:uRs''@"Ibu&&T[Yh_`'',Wdgup)i>=''BP02gqki3pE\`>mqQ+3*Da6X
	nQ&=7S.Zh''8<qJS]fr?;.EhHNn-B^*X$Lb@UGms+nroQB;Kh!fP.n/p''OOV6kJ)e03M81fj<Ds9D@r
	-`mQK4i5)GD]LY:47X!R$ec2&.o!GI8>"N#[eSbJIg+RO4C.AqHFY-C>*OJsg!nQjIAVR:''a&rrLL''
	KcU~>')
