accessing
colorNameTable
	"#(... #(name, (R G B)) ... "

	^#(
		( gray1 ( 0.9 0.9 0.9 ) )
		( gray2 ( 0.85 0.85 0.85 ) )
		( gray3 ( 0.8 0.8 0.8 ) )
		( gray4 ( 0.7 0.7 0.7 ) )
		( gray5 ( 0.6 0.6 0.6 ) )
		( gray6 ( 0.5 0.5 0.5 ) )
		( gray7 ( 0.4 0.4 0.4 ) )
		( gray8 ( 0.3 0.3 0.3 ) )
		( gray9 ( 0.2 0.2 0.2 ) )
		( red ( 0.75 0 0 ) )
		( lightred ( 1 0 0 ) )
		( darkred ( 0.5 0 0 ) )
		( white ( 1 1 1 ) )
	)
